/*===========================================================================+
 |      Copyright (c) 2006 Oracle Corporation, Redwood Shores, CA, USA       |
 |                         All rights reserved.                              |
 +===========================================================================+
 |  HISTORY                                                                  |
 +===========================================================================*/
 // javadoc_private

package oracle.apps.fnd.framework.toolbox.poplist.server;
import oracle.apps.fnd.common.VersionInfo;
import oracle.apps.fnd.framework.server.OAViewObjectImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class CurrencyVOImpl extends OAViewObjectImpl {

   public static final String RCS_ID="$Header: CurrencyVOImpl.java 120.1 2006/07/03 15:37:01 atgops1 noship $";
   public static final boolean RCS_ID_RECORDED =
	    VersionInfo.recordClassVersion(RCS_ID, "oracle.apps.fnd.framework.toolbox.poplist.server");
  /**
   *
   * This is the default constructor (do not remove)
   */
  public CurrencyVOImpl()
  {
  }
}
