//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------
// javadoc_private

package oracle.apps.fnd.framework.toolbox.poplist.server;

import oracle.apps.fnd.common.VersionInfo;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;


public class OrderStatusesVOImpl extends OAViewObjectImpl {

   public static final String RCS_ID="$Header: OrderStatusesVOImpl.java 120.2 2006/07/03 15:52:56 atgops1 noship $";
   public static final boolean RCS_ID_RECORDED =
	    VersionInfo.recordClassVersion(RCS_ID, "oracle.apps.fnd.framework.toolbox.poplist.server");


  /**
   *
   * This is the default constructor (do not remove)
   */
  public OrderStatusesVOImpl()
  {
  }
}