package mycompany.oracle.apps.fnd.framework.toolbox.schema.server;
import oracle.apps.fnd.framework.OAAttrValException;
import oracle.apps.fnd.framework.OAException;
import oracle.apps.fnd.framework.server.OAEntityDefImpl;
import oracle.apps.fnd.framework.toolbox.schema.server.PurchaseOrderLineEOImpl;

import oracle.jbo.Key;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;

//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class MyCompanyPurchaseOrderLinesEOImpl extends PurchaseOrderLineEOImpl {
    public static final int MAXATTRCONST = EntityDefImpl.getMaxAttrConst("oracle.apps.fnd.framework.toolbox.schema.server.PurchaseOrderLineEO");
    private static oracle.apps.fnd.framework.server.OAEntityDefImpl mDefinitionObject;

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public MyCompanyPurchaseOrderLinesEOImpl()
  {
  }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = 
                    (OAEntityDefImpl)EntityDefImpl.findDefObject("mycompany.oracle.apps.fnd.framework.toolbox.schema.server.MyCompanyPurchaseOrderLinesEO");
        }
        return mDefinitionObject;
    }

    public void setUnitPrice(Number value)
  {
  // Add validation before calling the super class method call.
  // The super class method will perform some validation and set the attribute
  // and hence, additional validation needs to be added before the super class
  // method call.
    if (value != null)
    {
      // Verify value is <= 10000.
      // Proper message with the message name should be seeded.
      if (value.compareTo(10000) > 0)
      {
         throw new OAAttrValException(OAException.TYP_ENTITY_OBJECT,
                                      getEntityDef().getFullName(),   // EO name
                                      getPrimaryKey(),                // EO PK
                                      "UnitPrice",                    // Attribute Name
                                      value,                          // Attribute value
                                      "AK",                           // Message product short name
                                      "FWK_TBX_T_PO_PRICE_EXCEEDED"); // Message name
      }
    }
    super.setUnitPrice(value);  }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(Number lineId) {
        return new Key(new Object[]{lineId});
    }
}
