/*===========================================================================+
 |   Copyright (c) 2001, 2003 Oracle Corporation, Redwood Shores, CA, USA    |
 |                         All rights reserved.                              |
 +===========================================================================+
 |  HISTORY                                                                  |
 +===========================================================================*/
// javadoc_private
package oracle.apps.fnd.framework.toolbox.labsolutions.server;

import oracle.apps.fnd.common.VersionInfo;
import oracle.apps.fnd.framework.server.OAViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Date;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class DebugLabEmpFullVORowImpl extends OAViewRowImpl {
    public static final int EMPLOYEEID = 0;
    public static final String RCS_ID="$Header: DebugLabEmpFullVORowImpl.java 120.1 2005/06/06 09:38:48 atgops1 noship $";
  public static final boolean RCS_ID_RECORDED =
        VersionInfo.recordClassVersion(RCS_ID, "%packagename%");
    public static final int FIRSTNAME = 1;
    public static final int LASTNAME = 2;
    public static final int EMPLOYEENAME = 3;
    public static final int SALARY = 4;
    public static final int STARTDATE = 5;
    public static final int ENDDATE = 6;
    public static final int EMPLOYEEEMAIL = 7;
    public static final int POSITIONCODE = 8;
    public static final int MANAGERID = 9;
    public static final int EMPLOYEEID1 = 10;
    public static final int MANAGERNAME = 11;
    public static final int MANAGEREMAIL = 12;
    public static final int POSITIONDISPLAY = 13;


    /**
     * 
     * This is the default constructor (do not remove)
     */
  public DebugLabEmpFullVORowImpl()
  {
  }

  /**
   * 
   * Gets EmployeeEO entity object.
   */
  public oracle.apps.fnd.framework.toolbox.schema.server.EmployeeEOImpl getEmployeeEO()
  {
    return (oracle.apps.fnd.framework.toolbox.schema.server.EmployeeEOImpl)getEntity(0);
  }

  /**
   * 
   * Gets EmployeeEO1 entity object.
   */
  public oracle.apps.fnd.framework.toolbox.schema.server.EmployeeEOImpl getEmployeeEO1()
  {
    return (oracle.apps.fnd.framework.toolbox.schema.server.EmployeeEOImpl)getEntity(1);
  }

  /**
   * 
   * Gets the attribute value for EMPLOYEE_ID using the alias name EmployeeId
   */
  public Number getEmployeeId()
  {
    return (Number)getAttributeInternal(EMPLOYEEID);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for EMPLOYEE_ID using the alias name EmployeeId
   */
  public void setEmployeeId(Number value)
  {
    setAttributeInternal(EMPLOYEEID, value);
  }

  /**
   * 
   * Gets the attribute value for FIRST_NAME using the alias name FirstName
   */
  public String getFirstName()
  {
    return (String)getAttributeInternal(FIRSTNAME);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for FIRST_NAME using the alias name FirstName
   */
  public void setFirstName(String value)
  {
    setAttributeInternal(FIRSTNAME, value);
  }

  /**
   * 
   * Gets the attribute value for LAST_NAME using the alias name LastName
   */
  public String getLastName()
  {
    return (String)getAttributeInternal(LASTNAME);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for LAST_NAME using the alias name LastName
   */
  public void setLastName(String value)
  {
    setAttributeInternal(LASTNAME, value);
  }

  /**
   * 
   * Gets the attribute value for FULL_NAME using the alias name EmployeeName
   */
  public String getEmployeeName()
  {
    return (String)getAttributeInternal(EMPLOYEENAME);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for FULL_NAME using the alias name EmployeeName
   */
  public void setEmployeeName(String value)
  {
    setAttributeInternal(EMPLOYEENAME, value);
  }

  /**
   * 
   * Gets the attribute value for SALARY using the alias name Salary
   */
  public Number getSalary()
  {
    return (Number)getAttributeInternal(SALARY);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for SALARY using the alias name Salary
   */
  public void setSalary(Number value)
  {
    setAttributeInternal(SALARY, value);
  }

  /**
   * 
   * Gets the attribute value for START_DATE using the alias name StartDate
   */
  public Date getStartDate()
  {
    return (Date)getAttributeInternal(STARTDATE);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for START_DATE using the alias name StartDate
   */
  public void setStartDate(Date value)
  {
    setAttributeInternal(STARTDATE, value);
  }

  /**
   * 
   * Gets the attribute value for END_DATE using the alias name EndDate
   */
  public Date getEndDate()
  {
    return (Date)getAttributeInternal(ENDDATE);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for END_DATE using the alias name EndDate
   */
  public void setEndDate(Date value)
  {
    setAttributeInternal(ENDDATE, value);
  }

  /**
   * 
   * Gets the attribute value for EMAIL_ADDRESS using the alias name EmployeeEmail
   */
  public String getEmployeeEmail()
  {
    return (String)getAttributeInternal(EMPLOYEEEMAIL);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for EMAIL_ADDRESS using the alias name EmployeeEmail
   */
  public void setEmployeeEmail(String value)
  {
    setAttributeInternal(EMPLOYEEEMAIL, value);
  }

  /**
   * 
   * Gets the attribute value for POSITION_CODE using the alias name PositionCode
   */
  public String getPositionCode()
  {
    return (String)getAttributeInternal(POSITIONCODE);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for POSITION_CODE using the alias name PositionCode
   */
  public void setPositionCode(String value)
  {
    setAttributeInternal(POSITIONCODE, value);
  }

  /**
   * 
   * Gets the attribute value for MANAGER_ID using the alias name ManagerId
   */
  public Number getManagerId()
  {
    return (Number)getAttributeInternal(MANAGERID);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for MANAGER_ID using the alias name ManagerId
   */
  public void setManagerId(Number value)
  {
    setAttributeInternal(MANAGERID, value);
  }

  /**
   * 
   * Gets the attribute value for EMPLOYEE_ID using the alias name EmployeeId1
   */
  public Number getEmployeeId1()
  {
    return (Number)getAttributeInternal(EMPLOYEEID1);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for EMPLOYEE_ID using the alias name EmployeeId1
   */
  public void setEmployeeId1(Number value)
  {
    setAttributeInternal(EMPLOYEEID1, value);
  }

  /**
   * 
   * Gets the attribute value for FULL_NAME using the alias name ManagerName
   */
  public String getManagerName()
  {
    return (String)getAttributeInternal(MANAGERNAME);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for FULL_NAME using the alias name ManagerName
   */
  public void setManagerName(String value)
  {
    setAttributeInternal(MANAGERNAME, value);
  }

  /**
   * 
   * Gets the attribute value for EMAIL_ADDRESS using the alias name ManagerEmail
   */
  public String getManagerEmail()
  {
    return (String)getAttributeInternal(MANAGEREMAIL);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for EMAIL_ADDRESS using the alias name ManagerEmail
   */
  public void setManagerEmail(String value)
  {
    setAttributeInternal(MANAGEREMAIL, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute PositionDisplay
   */
  public String getPositionDisplay()
  {
    return (String)getAttributeInternal(POSITIONDISPLAY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute PositionDisplay
   */
  public void setPositionDisplay(String value)
  {
    setAttributeInternal(POSITIONDISPLAY, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
        switch (index) {
        case EMPLOYEEID:
            return getEmployeeId();
        case FIRSTNAME:
            return getFirstName();
        case LASTNAME:
            return getLastName();
        case EMPLOYEENAME:
            return getEmployeeName();
        case SALARY:
            return getSalary();
        case STARTDATE:
            return getStartDate();
        case ENDDATE:
            return getEndDate();
        case EMPLOYEEEMAIL:
            return getEmployeeEmail();
        case POSITIONCODE:
            return getPositionCode();
        case MANAGERID:
            return getManagerId();
        case EMPLOYEEID1:
            return getEmployeeId1();
        case MANAGERNAME:
            return getManagerName();
        case MANAGEREMAIL:
            return getManagerEmail();
        case POSITIONDISPLAY:
            return getPositionDisplay();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
        switch (index) {
        case EMPLOYEEID:
            setEmployeeId((Number)value);
            return;
        case FIRSTNAME:
            setFirstName((String)value);
            return;
        case LASTNAME:
            setLastName((String)value);
            return;
        case EMPLOYEENAME:
            setEmployeeName((String)value);
            return;
        case SALARY:
            setSalary((Number)value);
            return;
        case STARTDATE:
            setStartDate((Date)value);
            return;
        case ENDDATE:
            setEndDate((Date)value);
            return;
        case EMPLOYEEEMAIL:
            setEmployeeEmail((String)value);
            return;
        case POSITIONCODE:
            setPositionCode((String)value);
            return;
        case MANAGERID:
            setManagerId((Number)value);
            return;
        case EMPLOYEEID1:
            setEmployeeId1((Number)value);
            return;
        case MANAGERNAME:
            setManagerName((String)value);
            return;
        case MANAGEREMAIL:
            setManagerEmail((String)value);
            return;
        case POSITIONDISPLAY:
            setPositionDisplay((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}