/*===========================================================================+
 |      Copyright (c) 2004 Oracle Corporation, Redwood Shores, CA, USA       |
 |                         All rights reserved.                              |
 +===========================================================================+
 |  HISTORY                                                                  |
 +===========================================================================*/
 // javadoc_private
package oracle.apps.fnd.framework.toolbox.labsolutions.server;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Date;

import oracle.apps.fnd.common.VersionInfo;

import oracle.apps.fnd.framework.server.OAViewRowImpl;

//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class SupplierSitesSVORowImpl extends OAViewRowImpl {

  protected static final int SUPPLIERID = 0;
  protected static final int SUPPLIERSITEID = 1;
  protected static final int SITENAME = 2;
  protected static final int PURCHASINGSITEFLAG = 3;
  protected static final int PAYMENTTERMSCODE = 4;
  protected static final int CARRIERCODE = 5;
  protected static final int ADDRESSID = 6;
  protected static final int STARTDATE = 7;
  protected static final int ENDDATE = 8;
  protected static final int SUPPLIERID1 = 9;
  protected static final int NAME = 10;
  /**
   * Oracle Applications internal source control identifier
   */
  public static final String RCS_ID="$Header: SupplierSitesSVORowImpl.java 120.4 2006/05/25 00:09:04 atgops1 noship $";
  /**
   * Oracle Applications internal source control identifier
   */
  public static final boolean RCS_ID_RECORDED =
        VersionInfo.recordClassVersion(RCS_ID, "oracle.apps.fnd.framework.toolbox.labsolutions.server");



  /**
   * 
   * This is the default constructor (do not remove)
   */
  public SupplierSitesSVORowImpl()
  {
  }

  /**
   * 
   * Gets SupplierSiteEO entity object.
   */
  public oracle.apps.fnd.framework.toolbox.schema.server.SupplierSiteEOImpl getSupplierSiteEO()
  {
    return (oracle.apps.fnd.framework.toolbox.schema.server.SupplierSiteEOImpl)getEntity(0);
  }

  /**
   * 
   * Gets SupplierEO entity object.
   */
  public oracle.apps.fnd.framework.toolbox.schema.server.SupplierEOImpl getSupplierEO()
  {
    return (oracle.apps.fnd.framework.toolbox.schema.server.SupplierEOImpl)getEntity(1);
  }






















  //  Generated method. Do not modify.

  //  Generated method. Do not modify.



}