//javadoc_private
package oracle.apps.fnd.framework.toolbox.labsolutions.server;
import oracle.apps.fnd.framework.server.OAViewObjectImpl;
import oracle.apps.fnd.common.VersionInfo;
import oracle.jbo.server.ViewObjectImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class TaskDetailsVOImpl extends OAViewObjectImpl 
{
  public static final String RCS_ID="$Header: TaskDetailsVOImpl.java 120.2 2008/04/03 07:26:02 atgops1 ship $";
  public static final boolean RCS_ID_RECORDED =
        VersionInfo.recordClassVersion(RCS_ID, "%packagename%");
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public TaskDetailsVOImpl()
  {
  }
}
