/*===========================================================================+
 |      Copyright (c) 2006 Oracle Corporation, Redwood Shores, CA, USA       |
 |                         All rights reserved.                              |
 +===========================================================================+
 |  HISTORY                                                                  |
 +===========================================================================*/
 // javadoc_private

package oracle.apps.fnd.framework.toolbox.samplelib.server;
import oracle.apps.fnd.common.VersionInfo;
import oracle.apps.fnd.framework.server.OAViewObjectImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class PurchaseOrderPPRVOImpl extends OAViewObjectImpl {

  public static final String RCS_ID="$Header: PurchaseOrderPPRVOImpl.java 120.1 2006/07/03 17:26:00 atgops1 noship $";
  public static final boolean RCS_ID_RECORDED =
    VersionInfo.recordClassVersion(RCS_ID, "oracle.apps.fnd.framework.toolbox.samplelib.server");

  /**
   *
   * This is the default constructor (do not remove)
   */
  public PurchaseOrderPPRVOImpl()
  {
  }
}
