package oracle.apps.fnd.framework.toolbox.tutorial.server;

import java.util.Vector;

import oracle.apps.fnd.cp.request.ConcurrentRequest;

import oracle.apps.fnd.cp.request.RequestSubmissionException;

import oracle.jbo.Row;
import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;
import oracle.apps.fnd.framework.server.OADBTransaction;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class InvoiceAMImpl extends OAApplicationModuleImpl {
    /**This is the default constructor (do not remove)
     */
    public InvoiceAMImpl() {
    }


    /**Sample main for debugging Business Components code using the tester.
     */
    public static void main(String[] args) {
        launchTester("oracle.apps.fnd.framework.toolbox.tutorial.server", /* package name */
      "InvoiceAMLocal" /* Configuration Name */);
    }
    
    public void init_bg_test(){
    Bg_testVOImpl vo= this.getBg_testVO1();
    vo.setWhereClauseParams(null);
    vo.setWhereClause(null);
    vo.setWhereClause("1=0");
    vo.executeQuery();
    }
    
    public void find_bg_test(){
        Bg_testVOImpl vo= this.getBg_testVO1();
        vo.setWhereClauseParams(null);
        vo.setWhereClause(null);
        vo.setWhereClause("1=1");
        vo.executeQuery();
    }
    
    public void commit_bg_test(){
      this.getOADBTransaction().commit();
    }
    
    public void add_bg_test(){
    Bg_testVOImpl vo=this.getBg_testVO1();
    Row row=vo.createRow();
    row.setNewRowState(Row.STATUS_NEW);
    vo.insertRow(row);
    }
    
    public void init(String invoice_num){
    Object[] params={invoice_num};
    InvoiceVOImpl vo=this.getInvoiceVO1();
    vo.setWhereClauseParams(null);
    vo.setWhereClause(null);
    vo.addWhereClause("INVOICE_NUM=:1");
    
    vo.setWhereClauseParams(params);
    vo.executeQuery();
    }
    
    public void apply()
    {
      getTransaction().commit();
    } // end apply()
    
    public void add(){
    
    InvoiceVOImpl vo=this.getInvoiceVO1();
    Row row=vo.createRow();
    row.setNewRowState(Row.STATUS_INITIALIZED);
    vo.insertRow(row);
    }
    
    public Integer request(){
    OADBTransaction tx=(OADBTransaction)this.getDBTransaction();
    java.sql.Connection pConnection=tx.getJdbcConnection();
    ConcurrentRequest cr=new ConcurrentRequest(pConnection);
    String appName="BG";
    String cpName="GLJOURNAL_BG_X";
    String cpDesc="GLJOURNAL_BG_X";
    Vector cpArgs=new Vector();
    cpArgs.addElement("2021");
    cpArgs.addElement("2021/01/01 00:00:00");
    cpArgs.addElement("2021/01/01 00:00:00");
    int requestid=0;
    try{
     requestid=cr.submitRequest(appName,cpName,cpDesc,null,false,cpArgs);}
     catch (RequestSubmissionException e){e.printStackTrace();}
     this.getOADBTransaction().commit();
     return requestid;
    }
   


    /**Container's getter for InvoiceVO1
     */
    public InvoiceVOImpl getInvoiceVO1() {
        return (InvoiceVOImpl)findViewObject("InvoiceVO1");
    }

    /**Container's getter for Bg_testVO1
     */
    public Bg_testVOImpl getBg_testVO1() {
        return (Bg_testVOImpl)findViewObject("Bg_testVO1");
    }
}
