package oracle.apps.fnd.framework.toolbox.tutorial.server;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Date;

import oracle.apps.fnd.common.VersionInfo;
import oracle.apps.fnd.framework.OAException;
import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.apps.fnd.framework.toolbox.schema.server.PurchaseOrderLineEOImpl;
import oracle.apps.fnd.framework.toolbox.schema.server.PurchaseOrderShipmentEOImpl;


//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------
// javadoc_private

public class PoLineShipFullVORowImpl extends OAViewRowImpl {

    public static final int LINEID = 0;
    public static final int HEADERID = 1;
    public static final int LINENUMBER = 2;
    public static final int ITEMID = 3;
    public static final int ITEMDESCRIPTION = 4;
    public static final int UNITOFMEASURE = 5;
    public static final int QUANTITY = 6;
    public static final int UNITPRICE = 7;
    public static final int SHIPMENTID = 8;
    public static final int LINEID1 = 9;
    public static final int SHIPMENTNUMBER = 10;
    public static final int NEEDBYDATE = 11;
    public static final int RECEIPTQUANTITY = 12;
    public static final int ORDERQUANTITY = 13;
    public static final int SHIPTOADDRESSID = 14;
    public static final int UOMDISPLAY = 15;
    public static final int LINETOTAL = 16;
    public static final int PODETAILSFULLVO1 = 17;
    protected static final int PODETAILSFULLVO = 17;
  public static final String RCS_ID="$Header: PoLineShipFullVORowImpl.java 120.5 2006/07/04 00:31:49 atgops1 noship $";
  public static final boolean RCS_ID_RECORDED =
        VersionInfo.recordClassVersion(RCS_ID, "oracle.apps.fnd.framework.toolbox.tutorial.server");


  // The following is required to support the creating the master/detail line
  // and shipment entities that have been "flattened" into a single row in
  // POLineShipFullVO with a 1:1 join.
  //
  // If you don't do this, BC4J will automatically treat them like peers and
  // try to set the po header id as the parent key for both entities.
  
  protected void create(oracle.jbo.AttributeList nvp) 
  { 
    PurchaseOrderLineEOImpl lineEO = (PurchaseOrderLineEOImpl)getEntity(0); 
    PurchaseOrderShipmentEOImpl shipmentEO = (PurchaseOrderShipmentEOImpl)getEntity(1); 
    
    try 
    { 
      // Create Lines EO 
      lineEO.create(nvp); 
      
      // Create Shipments EO 
      shipmentEO.create(lineEO); 
      
      // Calling this ensures that any personalization default values are
      // properly set since the OAF normally sets this in the super.create(), but
      // since this is not called in this workaround, we need another method
      // to ensure customer defaults are applied.
// The following method was introduced in OAF internal release 11.5.10J. Since
// the production release of the Toolbox must be able to run on 11.5.10I, this
// cannot be enabled.
//      setDefaultValue();
    } 
    catch (Exception ex) 
    { 
      lineEO.revert(); 
      shipmentEO.revert(); 

      if (ex instanceof oracle.jbo.JboException) 
      { 
        oracle.jbo.JboException jboEx = (oracle.jbo.JboException)ex; 
        // Developers have to do the mapping on their own becauce of the override. 
        jboEx.doEntityToVOMapping(getApplicationModule(), new oracle.jbo.ViewObject[]{getViewObject()}); 
        throw jboEx; 
      } 
      throw OAException.wrapperException(ex); 
    } 
  } // end create()



  /**
   * 
   * This is the default constructor (do not remove)
   */
  public PoLineShipFullVORowImpl()
  {
  }

  /**
   * 
   * Gets PurchaseOrderLineEO entity object.
   */
  public PurchaseOrderLineEOImpl getPurchaseOrderLineEO()
  {
    return (PurchaseOrderLineEOImpl)getEntity(0);
  }

  /**
   * 
   * Gets PurchaseOrderShipmentEO entity object.
   */
  public PurchaseOrderShipmentEOImpl getPurchaseOrderShipmentEO()
  {
    return (PurchaseOrderShipmentEOImpl)getEntity(1);
  }

  /**
   * 
   * Gets the attribute value for LINE_ID using the alias name LineId
   */
  public Number getLineId()
  {
    return (Number)getAttributeInternal(LINEID);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for LINE_ID using the alias name LineId
   */
  public void setLineId(Number value)
  {
    setAttributeInternal(LINEID, value);
  }

  /**
   * 
   * Gets the attribute value for HEADER_ID using the alias name HeaderId
   */
  public Number getHeaderId()
  {
    return (Number)getAttributeInternal(HEADERID);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for HEADER_ID using the alias name HeaderId
   */
  public void setHeaderId(Number value)
  {
    setAttributeInternal(HEADERID, value);
  }

  /**
   * 
   * Gets the attribute value for LINE_NUMBER using the alias name LineNumber
   */
  public Number getLineNumber()
  {
    return (Number)getAttributeInternal(LINENUMBER);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for LINE_NUMBER using the alias name LineNumber
   */
  public void setLineNumber(Number value)
  {
    setAttributeInternal(LINENUMBER, value);
  }

  /**
   * 
   * Gets the attribute value for ITEM_ID using the alias name ItemId
   */
  public Number getItemId()
  {
    return (Number)getAttributeInternal(ITEMID);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for ITEM_ID using the alias name ItemId
   */
  public void setItemId(Number value)
  {
    setAttributeInternal(ITEMID, value);
  }

  /**
   * 
   * Gets the attribute value for ITEM_DESCRIPTION using the alias name ItemDescription
   */
  public String getItemDescription()
  {
    return (String)getAttributeInternal(ITEMDESCRIPTION);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for ITEM_DESCRIPTION using the alias name ItemDescription
   */
  public void setItemDescription(String value)
  {
    setAttributeInternal(ITEMDESCRIPTION, value);
  }

  /**
   * 
   * Gets the attribute value for UNIT_OF_MEASURE using the alias name UnitOfMeasure
   */
  public String getUnitOfMeasure()
  {
    return (String)getAttributeInternal(UNITOFMEASURE);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for UNIT_OF_MEASURE using the alias name UnitOfMeasure
   */
  public void setUnitOfMeasure(String value)
  {
    setAttributeInternal(UNITOFMEASURE, value);
  }

  /**
   * 
   * Gets the attribute value for QUANTITY using the alias name Quantity
   */
  public Number getQuantity()
  {
    return (Number)getAttributeInternal(QUANTITY);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for QUANTITY using the alias name Quantity
   */
  public void setQuantity(Number value)
  {
    setAttributeInternal(QUANTITY, value);
  }

  /**
   * 
   * Gets the attribute value for UNIT_PRICE using the alias name UnitPrice
   */
  public Number getUnitPrice()
  {
    return (Number)getAttributeInternal(UNITPRICE);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for UNIT_PRICE using the alias name UnitPrice
   */
  public void setUnitPrice(Number value)
  {
    setAttributeInternal(UNITPRICE, value);
  }

  /**
   * 
   * Gets the attribute value for SHIPMENT_ID using the alias name ShipmentId
   */
  public Number getShipmentId()
  {
    return (Number)getAttributeInternal(SHIPMENTID);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for SHIPMENT_ID using the alias name ShipmentId
   */
  public void setShipmentId(Number value)
  {
    setAttributeInternal(SHIPMENTID, value);
  }

  /**
   * 
   * Gets the attribute value for LINE_ID using the alias name LineId1
   */
  public Number getLineId1()
  {
    return (Number)getAttributeInternal(LINEID1);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for LINE_ID using the alias name LineId1
   */
  public void setLineId1(Number value)
  {
    setAttributeInternal(LINEID1, value);
  }

  /**
   * 
   * Gets the attribute value for SHIPMENT_NUMBER using the alias name ShipmentNumber
   */
  public Number getShipmentNumber()
  {
    return (Number)getAttributeInternal(SHIPMENTNUMBER);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for SHIPMENT_NUMBER using the alias name ShipmentNumber
   */
  public void setShipmentNumber(Number value)
  {
    setAttributeInternal(SHIPMENTNUMBER, value);
  }

  /**
   * 
   * Gets the attribute value for NEED_BY_DATE using the alias name NeedByDate
   */
  public Date getNeedByDate()
  {
    return (Date)getAttributeInternal(NEEDBYDATE);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for NEED_BY_DATE using the alias name NeedByDate
   */
  public void setNeedByDate(Date value)
  {
    setAttributeInternal(NEEDBYDATE, value);
  }

  /**
   * 
   * Gets the attribute value for RECEIPT_QUANTITY using the alias name ReceiptQuantity
   */
  public Number getReceiptQuantity()
  {
    return (Number)getAttributeInternal(RECEIPTQUANTITY);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for RECEIPT_QUANTITY using the alias name ReceiptQuantity
   */
  public void setReceiptQuantity(Number value)
  {
    setAttributeInternal(RECEIPTQUANTITY, value);
  }

  /**
   * 
   * Gets the attribute value for ORDER_QUANTITY using the alias name OrderQuantity
   */
  public Number getOrderQuantity()
  {
    return (Number)getAttributeInternal(ORDERQUANTITY);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for ORDER_QUANTITY using the alias name OrderQuantity
   */
  public void setOrderQuantity(Number value)
  {
    setAttributeInternal(ORDERQUANTITY, value);
  }

  /**
   * 
   * Gets the attribute value for SHIP_TO_ADDRESS_ID using the alias name ShipToAddressId
   */
  public Number getShipToAddressId()
  {
    return (Number)getAttributeInternal(SHIPTOADDRESSID);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for SHIP_TO_ADDRESS_ID using the alias name ShipToAddressId
   */
  public void setShipToAddressId(Number value)
  {
    setAttributeInternal(SHIPTOADDRESSID, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute UomDisplay
   */
  public String getUomDisplay()
  {
    return (String)getAttributeInternal(UOMDISPLAY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute UomDisplay
   */
  public void setUomDisplay(String value)
  {
    setAttributeInternal(UOMDISPLAY, value);
  }

  /**
   * 
   * Gets the attribute value for $none$ using the alias name LineTotal
   */
  public Number getLineTotal()
  {
    return (Number)getAttributeInternal(LINETOTAL);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for $none$ using the alias name LineTotal
   */
  public void setLineTotal(Number value)
  {
    setAttributeInternal(LINETOTAL, value);
  }

  /**
   * 
   * Gets the associated <code>Row</code> using master-detail link PODetailsFullVO
   */
  public oracle.jbo.Row getPODetailsFullVO()
  {
    return (oracle.jbo.Row)getAttributeInternal(PODETAILSFULLVO);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
        switch (index) {
        case LINEID:
            return getLineId();
        case HEADERID:
            return getHeaderId();
        case LINENUMBER:
            return getLineNumber();
        case ITEMID:
            return getItemId();
        case ITEMDESCRIPTION:
            return getItemDescription();
        case UNITOFMEASURE:
            return getUnitOfMeasure();
        case QUANTITY:
            return getQuantity();
        case UNITPRICE:
            return getUnitPrice();
        case SHIPMENTID:
            return getShipmentId();
        case LINEID1:
            return getLineId1();
        case SHIPMENTNUMBER:
            return getShipmentNumber();
        case NEEDBYDATE:
            return getNeedByDate();
        case RECEIPTQUANTITY:
            return getReceiptQuantity();
        case ORDERQUANTITY:
            return getOrderQuantity();
        case SHIPTOADDRESSID:
            return getShipToAddressId();
        case UOMDISPLAY:
            return getUomDisplay();
        case LINETOTAL:
            return getLineTotal();
        case PODETAILSFULLVO1:
            return getPoDetailsFullVO1();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
        switch (index) {
        case LINEID:
            setLineId((Number)value);
            return;
        case HEADERID:
            setHeaderId((Number)value);
            return;
        case LINENUMBER:
            setLineNumber((Number)value);
            return;
        case ITEMID:
            setItemId((Number)value);
            return;
        case ITEMDESCRIPTION:
            setItemDescription((String)value);
            return;
        case UNITOFMEASURE:
            setUnitOfMeasure((String)value);
            return;
        case QUANTITY:
            setQuantity((Number)value);
            return;
        case UNITPRICE:
            setUnitPrice((Number)value);
            return;
        case SHIPMENTID:
            setShipmentId((Number)value);
            return;
        case LINEID1:
            setLineId1((Number)value);
            return;
        case SHIPMENTNUMBER:
            setShipmentNumber((Number)value);
            return;
        case NEEDBYDATE:
            setNeedByDate((Date)value);
            return;
        case RECEIPTQUANTITY:
            setReceiptQuantity((Number)value);
            return;
        case ORDERQUANTITY:
            setOrderQuantity((Number)value);
            return;
        case SHIPTOADDRESSID:
            setShipToAddressId((Number)value);
            return;
        case UOMDISPLAY:
            setUomDisplay((String)value);
            return;
        case LINETOTAL:
            setLineTotal((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

  /**
   * 
   * Gets the associated <code>Row</code> using master-detail link PoDetailsFullVO1
   */
  public oracle.jbo.Row getPoDetailsFullVO1()
  {
    return (oracle.jbo.Row)getAttributeInternal(PODETAILSFULLVO1);
  }
}
