/*===========================================================================+
 |      Copyright (c) 2001, 2018 Oracle Corporation, Redwood Shores, CA, USA       |
 |                         All rights reserved.                              |
 +===========================================================================+
 |  HISTORY                                                                  |
 +===========================================================================*/
// javadoc_private
package oracle.apps.fnd.framework.toolbox.tutorial.server;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Date;

import oracle.apps.fnd.common.VersionInfo;
import oracle.apps.fnd.framework.server.OAViewRowImpl;

//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class PoSimpleSummaryVORowImpl extends OAViewRowImpl {

    public static final int ORDERNUMBER = 0;
    public static final String RCS_ID="$Header: PoSimpleSummaryVORowImpl.java 120.2.12020000.3 2018/04/10 05:40:29 lmodugul ship $";
  public static final boolean RCS_ID_RECORDED =
        VersionInfo.recordClassVersion(RCS_ID, "oracle.apps.fnd.framework.toolbox.tutorial.server");
    public static final int DESCRIPTION = 1;
    public static final int CURRENCYCODE = 2;
    public static final int CREATIONDATE = 3;
    public static final int BUYERID = 4;
    public static final int BUYERNAME = 5;
    public static final int SUPPLIERNAME = 6;
    public static final int BUYEREMAIL = 7;
    public static final int ORDERTOTAL = 8;
    public static final int SUPPLIERID = 9;
    public static final int EMPLOYEEID = 10;
    public static final int STATUSCODE = 11;
    public static final int CONFIRMFLAG = 12;


    /**
     *
     * This is the default constructor (do not remove)
     */
  public PoSimpleSummaryVORowImpl()
  {
  }

  /**
   * 
   * Gets PurchaseOrderHeaderEO entity object.
   */
  public oracle.apps.fnd.framework.toolbox.schema.server.PurchaseOrderHeaderEOImpl getPurchaseOrderHeaderEO()
  {
    return (oracle.apps.fnd.framework.toolbox.schema.server.PurchaseOrderHeaderEOImpl)getEntity(0);
  }

  /**
   * 
   * Gets EmployeeEO entity object.
   */
  public oracle.apps.fnd.framework.toolbox.schema.server.EmployeeEOImpl getEmployeeEO()
  {
    return (oracle.apps.fnd.framework.toolbox.schema.server.EmployeeEOImpl)getEntity(1);
  }

  /**
   * 
   * Gets SupplierEO entity object.
   */
  public oracle.apps.fnd.framework.toolbox.schema.server.SupplierEOImpl getSupplierEO()
  {
    return (oracle.apps.fnd.framework.toolbox.schema.server.SupplierEOImpl)getEntity(2);
  }



  /**
   * 
   * Gets the attribute value for DESCRIPTION using the alias name Description
   */
  public String getDescription()
  {
    return (String)getAttributeInternal(DESCRIPTION);
  }

  public void setDescription(String value)
  {
  }

  /**
   * 
   * Gets the attribute value for CURRENCY_CODE using the alias name CurrencyCode
   */
  public String getCurrencyCode()
  {
    return (String)getAttributeInternal(CURRENCYCODE);
  }

  public void setCurrencyCode(String value)
  {
  }

  /**
   * 
   * Gets the attribute value for CREATION_DATE using the alias name CreationDate
   */
  public Date getCreationDate()
  {
    return (Date)getAttributeInternal(CREATIONDATE);
  }

  public void setCreationDate(Date value)
  {
  }

  /**
   * 
   * Gets the attribute value for BUYER_ID using the alias name BuyerId
   */
  public Number getBuyerId()
  {
    return (Number)getAttributeInternal(BUYERID);
  }

  public void setBuyerId(Number value)
  {
  }










  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
        switch (index) {
        case ORDERNUMBER:
            return getOrderNumber();
        case DESCRIPTION:
            return getDescription();
        case CURRENCYCODE:
            return getCurrencyCode();
        case CREATIONDATE:
            return getCreationDate();
        case BUYERID:
            return getBuyerId();
        case BUYERNAME:
            return getBuyerName();
        case SUPPLIERNAME:
            return getSupplierName();
        case BUYEREMAIL:
            return getBuyerEmail();
        case ORDERTOTAL:
            return getOrderTotal();
        case SUPPLIERID:
            return getSupplierId();
        case EMPLOYEEID:
            return getEmployeeId();
        case STATUSCODE:
            return getStatusCode();
        case CONFIRMFLAG:
            return getConfirmFlag();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
        switch (index) {
        case ORDERNUMBER:
            setOrderNumber((Number)value);
            return;
        case DESCRIPTION:
            setDescription((String)value);
            return;
        case CURRENCYCODE:
            setCurrencyCode((String)value);
            return;
        case BUYERID:
            setBuyerId((Number)value);
            return;
        case BUYERNAME:
            setBuyerName((String)value);
            return;
        case SUPPLIERNAME:
            setSupplierName((String)value);
            return;
        case BUYEREMAIL:
            setBuyerEmail((String)value);
            return;
        case SUPPLIERID:
            setSupplierId((Number)value);
            return;
        case EMPLOYEEID:
            setEmployeeId((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

  /**
   * 
   * Gets the attribute value for the calculated attribute OrderTotal
   */
  public Number getOrderTotal()
  {
    return (Number)getAttributeInternal(ORDERTOTAL);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute OrderTotal
   */
  public void setOrderTotal(Number value)
  {
    setAttributeInternal(ORDERTOTAL, value);
  }

  /**
   * 
   * Gets the attribute value for EMPLOYEE_ID using the alias name EmployeeId
   */
  public Number getEmployeeId()
  {
    return (Number)getAttributeInternal(EMPLOYEEID);
  }

  public void setEmployeeId(Number value)
  {
  }

  /**
   * 
   * Gets the attribute value for SUPPLIER_ID using the alias name SupplierId
   */
  public Number getSupplierId()
  {
    return (Number)getAttributeInternal(SUPPLIERID);
  }

  public void setSupplierId(Number value)
  {
  }

  /**
   * 
   * Gets the attribute value for HEADER_ID using the alias name OrderNumber
   */
  public Number getOrderNumber()
  {
    return (Number)getAttributeInternal(ORDERNUMBER);
  }

  public void setOrderNumber(Number value)
  {
  }

  /**
   * 
   * Gets the attribute value for FULL_NAME using the alias name BuyerName
   */
  public String getBuyerName()
  {
    return (String)getAttributeInternal(BUYERNAME);
  }

  public void setBuyerName(String value)
  {
  }

  /**
   * 
   * Gets the attribute value for NAME using the alias name SupplierName
   */
  public String getSupplierName()
  {
    return (String)getAttributeInternal(SUPPLIERNAME);
  }

  public void setSupplierName(String value)
  {
  }

  /**
   * 
   * Gets the attribute value for EMAIL_ADDRESS using the alias name BuyerEmail
   */
  public String getBuyerEmail()
  {
    return (String)getAttributeInternal(BUYEREMAIL);
  }

  public void setBuyerEmail(String value)
  {
  }

    /**Sample exportable method.
     */
    public void samplePoSimpleSummaryVORowImplExportable() {
    }

    /**Sample exportable method.
     */
    public void samplePoSimpleSummaryVORowImplExportable2(String testParam1) {
    }

    /**Gets the attribute value for STATUS_CODE using the alias name StatusCode
     */
    public String getStatusCode() {
        return (String) getAttributeInternal(STATUSCODE);
    }

  /**Gets the attribute value for CONFIRM_FLAG using the alias name ConfirmFlag
   */
  public String getConfirmFlag()
  {
    return (String) getAttributeInternal(CONFIRMFLAG);
  }

  /**Sets <code>value</code> as attribute value for CONFIRM_FLAG using the alias name ConfirmFlag
   */
  public void setConfirmFlag(String value)
  {
    setAttributeInternal(CONFIRMFLAG, value);
  }
}
