package oracle.apps.fnd.framework.toolbox.tutorial.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Date;
import oracle.apps.fnd.common.VersionInfo;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------
// javadoc_private

public class PoSummarySimpleExpVORowImpl extends OAViewRowImpl {

    public static final int ORDERNUMBER = 0;
    public static final String RCS_ID="$Header: PoSummarySimpleExpVORowImpl.java 120.1 2005/06/06 16:07:36 atgops1 noship $";
  public static final boolean RCS_ID_RECORDED =
        VersionInfo.recordClassVersion(RCS_ID, "oracle.apps.fnd.framework.toolbox.tutorial.server");
    public static final int DESCRIPTION = 1;
    public static final int STATUSCODE = 2;
    public static final int SUPPLIERID = 3;
    public static final int CURRENCYCODE = 4;
    public static final int BUYERID = 5;
    public static final int BUYERNAME = 6;
    public static final int BUYEREMAIL = 7;
    public static final int SUPPLIERNAME = 8;
    public static final int STATUSDISPLAY = 9;
    public static final int ORDERTOTAL = 10;
    public static final int CREATIONDATE = 11;


    /**
     * 
     * This is the default constructor (do not remove)
     */
  public PoSummarySimpleExpVORowImpl()
  {
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute OrderNumber
   */
  public Number getOrderNumber()
  {
    return (Number)getAttributeInternal(ORDERNUMBER);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute OrderNumber
   */
  public void setOrderNumber(Number value)
  {
    setAttributeInternal(ORDERNUMBER, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute Description
   */
  public String getDescription()
  {
    return (String)getAttributeInternal(DESCRIPTION);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute Description
   */
  public void setDescription(String value)
  {
    setAttributeInternal(DESCRIPTION, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute StatusCode
   */
  public String getStatusCode()
  {
    return (String)getAttributeInternal(STATUSCODE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute StatusCode
   */
  public void setStatusCode(String value)
  {
    setAttributeInternal(STATUSCODE, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute SupplierId
   */
  public Number getSupplierId()
  {
    return (Number)getAttributeInternal(SUPPLIERID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute SupplierId
   */
  public void setSupplierId(Number value)
  {
    setAttributeInternal(SUPPLIERID, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute CurrencyCode
   */
  public String getCurrencyCode()
  {
    return (String)getAttributeInternal(CURRENCYCODE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute CurrencyCode
   */
  public void setCurrencyCode(String value)
  {
    setAttributeInternal(CURRENCYCODE, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute BuyerId
   */
  public Number getBuyerId()
  {
    return (Number)getAttributeInternal(BUYERID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute BuyerId
   */
  public void setBuyerId(Number value)
  {
    setAttributeInternal(BUYERID, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute BuyerName
   */
  public String getBuyerName()
  {
    return (String)getAttributeInternal(BUYERNAME);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute BuyerName
   */
  public void setBuyerName(String value)
  {
    setAttributeInternal(BUYERNAME, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute BuyerEmail
   */
  public String getBuyerEmail()
  {
    return (String)getAttributeInternal(BUYEREMAIL);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute BuyerEmail
   */
  public void setBuyerEmail(String value)
  {
    setAttributeInternal(BUYEREMAIL, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute SupplierName
   */
  public String getSupplierName()
  {
    return (String)getAttributeInternal(SUPPLIERNAME);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute SupplierName
   */
  public void setSupplierName(String value)
  {
    setAttributeInternal(SUPPLIERNAME, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute StatusDisplay
   */
  public String getStatusDisplay()
  {
    return (String)getAttributeInternal(STATUSDISPLAY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute StatusDisplay
   */
  public void setStatusDisplay(String value)
  {
    setAttributeInternal(STATUSDISPLAY, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute OrderTotal
   */
  public Number getOrderTotal()
  {
    return (Number)getAttributeInternal(ORDERTOTAL);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute OrderTotal
   */
  public void setOrderTotal(Number value)
  {
    setAttributeInternal(ORDERTOTAL, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute CreationDate
   */
  public Date getCreationDate()
  {
    return (Date)getAttributeInternal(CREATIONDATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute CreationDate
   */
  public void setCreationDate(Date value)
  {
    setAttributeInternal(CREATIONDATE, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
        switch (index) {
        case ORDERNUMBER:
            return getOrderNumber();
        case DESCRIPTION:
            return getDescription();
        case STATUSCODE:
            return getStatusCode();
        case SUPPLIERID:
            return getSupplierId();
        case CURRENCYCODE:
            return getCurrencyCode();
        case BUYERID:
            return getBuyerId();
        case BUYERNAME:
            return getBuyerName();
        case BUYEREMAIL:
            return getBuyerEmail();
        case SUPPLIERNAME:
            return getSupplierName();
        case STATUSDISPLAY:
            return getStatusDisplay();
        case ORDERTOTAL:
            return getOrderTotal();
        case CREATIONDATE:
            return getCreationDate();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
        switch (index) {
        case ORDERNUMBER:
            setOrderNumber((Number)value);
            return;
        case DESCRIPTION:
            setDescription((String)value);
            return;
        case STATUSCODE:
            setStatusCode((String)value);
            return;
        case SUPPLIERID:
            setSupplierId((Number)value);
            return;
        case CURRENCYCODE:
            setCurrencyCode((String)value);
            return;
        case BUYERID:
            setBuyerId((Number)value);
            return;
        case BUYERNAME:
            setBuyerName((String)value);
            return;
        case BUYEREMAIL:
            setBuyerEmail((String)value);
            return;
        case SUPPLIERNAME:
            setSupplierName((String)value);
            return;
        case STATUSDISPLAY:
            setStatusDisplay((String)value);
            return;
        case ORDERTOTAL:
            setOrderTotal((Number)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
