/*===========================================================================+
 |      Copyright (c) 2001 Oracle Corporation, Redwood Shores, CA, USA       |
 |                         All rights reserved.                              |
 +===========================================================================+
 |  HISTORY                                                                  |
 +===========================================================================*/
 //  javadoc_private
package oracle.apps.fnd.framework.toolbox.tutorial.server;

import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Date;

import oracle.apps.fnd.common.VersionInfo;
import oracle.apps.fnd.framework.server.OAViewRowImpl;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------

public class SupplierSummaryVORowImpl extends OAViewRowImpl {

  // Required for Applications source control
    public static final int NAME = 0;
    public static final String RCS_ID="$Header: SupplierSummaryVORowImpl.java 120.2 2006/07/04 02:24:52 atgops1 noship $";
  public static final boolean RCS_ID_RECORDED =
        VersionInfo.recordClassVersion(RCS_ID, "oracle.apps.fnd.framework.toolbox.tutorial.server");
    public static final int SUPPLIERID = 1;
    public static final int STARTDATE = 2;
    public static final int ENDDATE = 3;
    public static final int ONHOLDDISPLAY = 4;
    public static final int ONHOLDFLAG = 5;


    /**
     *
     * This is the default constructor (do not remove)
     */
  public SupplierSummaryVORowImpl()
  {
  }

  /**
   * 
   * Gets SupplierEO entity object.
   */
  public oracle.apps.fnd.framework.toolbox.schema.server.SupplierEOImpl getSupplierEO()
  {
    return (oracle.apps.fnd.framework.toolbox.schema.server.SupplierEOImpl)getEntity(0);
  }

  /**
   * 
   * Gets the attribute value for NAME using the alias name Name
   */
  public String getName()
  {
    return (String)getAttributeInternal(NAME);
  }

  public void setName(String value)
  {
  }

  /**
   * 
   * Gets the attribute value for SUPPLIER_ID using the alias name SupplierId
   */
  public Number getSupplierId()
  {
    return (Number)getAttributeInternal(SUPPLIERID);
  }

  public void setSupplierId(Number value)
  {
  }

  /**
   * 
   * Gets the attribute value for START_DATE using the alias name StartDate
   */
  public Date getStartDate()
  {
    return (Date)getAttributeInternal(STARTDATE);
  }

  public void setStartDate(Date value)
  {
  }

  /**
   * 
   * Gets the attribute value for END_DATE using the alias name EndDate
   */
  public Date getEndDate()
  {
    return (Date)getAttributeInternal(ENDDATE);
  }

  public void setEndDate(Date value)
  {
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
        switch (index) {
        case NAME:
            return getName();
        case SUPPLIERID:
            return getSupplierId();
        case STARTDATE:
            return getStartDate();
        case ENDDATE:
            return getEndDate();
        case ONHOLDDISPLAY:
            return getOnHoldDisplay();
        case ONHOLDFLAG:
            return getOnHoldFlag();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
        switch (index) {
        case NAME:
            setName((String)value);
            return;
        case SUPPLIERID:
            setSupplierId((Number)value);
            return;
        case STARTDATE:
            setStartDate((Date)value);
            return;
        case ENDDATE:
            setEndDate((Date)value);
            return;
        case ONHOLDDISPLAY:
            setOnHoldDisplay((String)value);
            return;
        case ONHOLDFLAG:
            setOnHoldFlag((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

  /**
   * 
   * Gets the attribute value for the calculated attribute OnHoldDisplay
   */
  public String getOnHoldDisplay()
  {
    return (String)getAttributeInternal(ONHOLDDISPLAY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute OnHoldDisplay
   */
  public void setOnHoldDisplay(String value)
  {
    setAttributeInternal(ONHOLDDISPLAY, value);
  }

  /**
   * 
   * Gets the attribute value for ON_HOLD_FLAG using the alias name OnHoldFlag
   */
  public String getOnHoldFlag()
  {
    return (String)getAttributeInternal(ONHOLDFLAG);
  }

  /**
   * 
   * Sets <code>value</code> as attribute value for ON_HOLD_FLAG using the alias name OnHoldFlag
   */
  public void setOnHoldFlag(String value)
  {
    setAttributeInternal(ONHOLDFLAG, value);
  }
}