package oracle.apps.fnd.framework.toolbox.tutorial.server;
import oracle.apps.fnd.framework.server.OAViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.jbo.domain.Date;
import oracle.apps.fnd.common.VersionInfo;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------
// javadoc_private

public class SuppliersExpVORowImpl extends OAViewRowImpl {

    public static final int SUPPLIERID = 0;
    public static final String RCS_ID="$Header: SuppliersExpVORowImpl.java 120.1 2005/06/06 16:44:43 atgops1 noship $";
  public static final boolean RCS_ID_RECORDED =
        VersionInfo.recordClassVersion(RCS_ID, "oracle.apps.fnd.framework.toolbox.tutorial.server");
    public static final int NAME = 1;
    public static final int ONHOLDFLAG = 2;
    public static final int STARTDATE = 3;
    public static final int ENDDATE = 4;
    public static final int ONHOLDDISPLAY = 5;


    /**
     * 
     * This is the default constructor (do not remove)
     */
  public SuppliersExpVORowImpl()
  {
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute SupplierId
   */
  public Number getSupplierId()
  {
    return (Number)getAttributeInternal(SUPPLIERID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute SupplierId
   */
  public void setSupplierId(Number value)
  {
    setAttributeInternal(SUPPLIERID, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute Name
   */
  public String getName()
  {
    return (String)getAttributeInternal(NAME);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute Name
   */
  public void setName(String value)
  {
    setAttributeInternal(NAME, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute OnHoldFlag
   */
  public String getOnHoldFlag()
  {
    return (String)getAttributeInternal(ONHOLDFLAG);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute OnHoldFlag
   */
  public void setOnHoldFlag(String value)
  {
    setAttributeInternal(ONHOLDFLAG, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute StartDate
   */
  public Date getStartDate()
  {
    return (Date)getAttributeInternal(STARTDATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute StartDate
   */
  public void setStartDate(Date value)
  {
    setAttributeInternal(STARTDATE, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute EndDate
   */
  public Date getEndDate()
  {
    return (Date)getAttributeInternal(ENDDATE);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute EndDate
   */
  public void setEndDate(Date value)
  {
    setAttributeInternal(ENDDATE, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute OnHoldDisplay
   */
  public String getOnHoldDisplay()
  {
    return (String)getAttributeInternal(ONHOLDDISPLAY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute OnHoldDisplay
   */
  public void setOnHoldDisplay(String value)
  {
    setAttributeInternal(ONHOLDDISPLAY, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
        switch (index) {
        case SUPPLIERID:
            return getSupplierId();
        case NAME:
            return getName();
        case ONHOLDFLAG:
            return getOnHoldFlag();
        case STARTDATE:
            return getStartDate();
        case ENDDATE:
            return getEndDate();
        case ONHOLDDISPLAY:
            return getOnHoldDisplay();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
        switch (index) {
        case SUPPLIERID:
            setSupplierId((Number)value);
            return;
        case NAME:
            setName((String)value);
            return;
        case ONHOLDFLAG:
            setOnHoldFlag((String)value);
            return;
        case STARTDATE:
            setStartDate((Date)value);
            return;
        case ENDDATE:
            setEndDate((Date)value);
            return;
        case ONHOLDDISPLAY:
            setOnHoldDisplay((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
