package oracle.apps.fnd.framework.toolbox.lov.server;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;
import oracle.apps.fnd.common.VersionInfo;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------
// javadoc_private

public class AllPOsExpVOImpl extends OAViewObjectImpl {
  public static final String RCS_ID="$Header: AllPOsExpVOImpl.java 120.2 2006/07/03 14:35:30 atgops1 noship $";
  public static final boolean RCS_ID_RECORDED =
        VersionInfo.recordClassVersion(RCS_ID, "oracle.apps.fnd.framework.toolbox.lov.server");

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public AllPOsExpVOImpl()
  {
  }
}
