package oracle.apps.fnd.framework.toolbox.lov.server;
/*========================================================================+
 |   Copyright (c) 2001, 2020 Oracle Corporation, Redwood Shores, CA, USA |
 |                      All rights reserved.                              |
 +========================================================================+
 |  HISTORY                                                               |
 | 5-Nov-2014 SRSIDDAM Created.                                           |
 +========================================================================+
 */
import oracle.apps.fnd.common.VersionInfo;
import oracle.apps.fnd.framework.server.OAApplicationModuleImpl;
import oracle.apps.fnd.framework.server.OAViewObjectImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class EmpDesignationLOVAMImpl extends OAApplicationModuleImpl {
    public static final String RCS_ID = "$Header: EmpDesignationLOVAMImpl.java 120.0.12020000.1 2020/01/08 11:56:42 spunam noship $";
    public static final boolean RCS_ID_RECORDED = VersionInfo.recordClassVersion(RCS_ID, "oracle.apps.fnd.framework.toolbox.lov.server"); 
    /**This is the default constructor (do not remove)
     */
    public EmpDesignationLOVAMImpl() {
    }

    /**Container's getter for EmpDesignationLOVVO1
     */
    public OAViewObjectImpl getEmpDesignationLOVVO1() {
        return (OAViewObjectImpl)findViewObject("EmpDesignationLOVVO1");
    }

    /**Sample main for debugging Business Components code using the tester.
     */
    public static void main(String[] args) {
        launchTester("oracle.apps.fnd.framework.toolbox.lov.server", /* package name */
      "EmpDesignationLOVAMLocal" /* Configuration Name */);
    }
}
