package oracle.apps.fnd.framework.toolbox.lov.server;

import oracle.apps.fnd.framework.server.OAViewRowImpl;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.domain.Number;
import oracle.apps.fnd.common.VersionInfo;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------
// javadoc_private

public class SuppliersLOVVORowImpl extends OAViewRowImpl {

    public static final int NAME = 0;
    public static final String RCS_ID="$Header: SuppliersLOVVORowImpl.java 120.2 2006/07/03 15:07:13 atgops1 noship $";
  public static final boolean RCS_ID_RECORDED =
        VersionInfo.recordClassVersion(RCS_ID, "oracle.apps.fnd.framework.toolbox.lov.server");
    public static final int SUPPLIERID = 1;
    public static final int ONHOLDDISPLAY = 2;


    /**
     *
     * This is the default constructor (do not remove)
     */
  public SuppliersLOVVORowImpl()
  {
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute Name
   */
  public String getName()
  {
    return (String)getAttributeInternal(NAME);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute Name
   */
  public void setName(String value)
  {
    setAttributeInternal(NAME, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute SupplierId
   */
  public Number getSupplierId()
  {
    return (Number)getAttributeInternal(SUPPLIERID);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute SupplierId
   */
  public void setSupplierId(Number value)
  {
    setAttributeInternal(SUPPLIERID, value);
  }

  /**
   * 
   * Gets the attribute value for the calculated attribute OnHoldDisplay
   */
  public String getOnHoldDisplay()
  {
    return (String)getAttributeInternal(ONHOLDDISPLAY);
  }

  /**
   * 
   * Sets <code>value</code> as the attribute value for the calculated attribute OnHoldDisplay
   */
  public void setOnHoldDisplay(String value)
  {
    setAttributeInternal(ONHOLDDISPLAY, value);
  }
  //  Generated method. Do not modify.

  protected Object getAttrInvokeAccessor(int index, AttributeDefImpl attrDef) throws Exception
  {
        switch (index) {
        case NAME:
            return getName();
        case SUPPLIERID:
            return getSupplierId();
        case ONHOLDDISPLAY:
            return getOnHoldDisplay();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }
  //  Generated method. Do not modify.

  protected void setAttrInvokeAccessor(int index, Object value, AttributeDefImpl attrDef) throws Exception
  {
        switch (index) {
        case NAME:
            setName((String)value);
            return;
        case SUPPLIERID:
            setSupplierId((Number)value);
            return;
        case ONHOLDDISPLAY:
            setOnHoldDisplay((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
