package oracle.apps.fnd.framework.toolbox.lov.server;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;
import oracle.jbo.server.ViewObjectImpl;
import oracle.jbo.RowIterator;
import oracle.apps.fnd.common.VersionInfo;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------
// javadoc_private

public class SuppliersLOVVOImpl extends OAViewObjectImpl 
{
  public static final String RCS_ID="$Header: SuppliersLOVVOImpl.java 120.1 2005/06/06 11:35:40 atgops1 noship $";
  public static final boolean RCS_ID_RECORDED =
        VersionInfo.recordClassVersion(RCS_ID, "oracle.apps.fnd.framework.toolbox.lov.server");

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public SuppliersLOVVOImpl()
  {
  }
}
