package oracle.apps.fnd.framework.toolbox.schema.server;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;
import oracle.jbo.domain.Number;
import oracle.apps.fnd.common.VersionInfo;
//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------
// javadoc_private

public class PoLineNumVVOImpl extends OAViewObjectImpl {

  public static final String RCS_ID="$Header: PoLineNumVVOImpl.java 120.2 2006/07/03 20:39:10 atgops1 noship $";
  public static final boolean RCS_ID_RECORDED =
        VersionInfo.recordClassVersion(RCS_ID, "oracle.apps.fnd.framework.toolbox.schema.server");

  public void initQuery(Number headerId, Number lineNumber)
  {
    setWhereClauseParams(null); // Always reset
    setWhereClauseParam(0, headerId);
    setWhereClauseParam(1, lineNumber);
    executeQuery();

  }
  
  /**
   * 
   * This is the default constructor (do not remove)
   */
  public PoLineNumVVOImpl()
  {
  }
}
