package oracle.apps.fnd.framework.toolbox.schema.server;

import oracle.apps.fnd.framework.server.OAViewObjectImpl;
import oracle.apps.fnd.common.VersionInfo;

public class SupplierNameVVOImpl extends OAViewObjectImpl {

  public static final String RCS_ID="$Header: SupplierNameVVOImpl.java 120.2 2006/07/03 22:55:11 atgops1 noship $";
  public static final boolean RCS_ID_RECORDED =
        VersionInfo.recordClassVersion(RCS_ID, "oracle.apps.fnd.framework.toolbox.schema.server");

  public void initQuery(String name)
  {
    setWhereClauseParams(null); // Always reset
    setWhereClauseParam(0, name);
    executeQuery();
  }

//  ---------------------------------------------------------------
//  ---    File generated by Oracle Business Components for Java.
//  ---------------------------------------------------------------
// javadoc_private

  /**
   * 
   * This is the default constructor (do not remove)
   */
  public SupplierNameVVOImpl()
  {
  }
}
