package oracle.apps.fnd.framework.toolbox.tutorial2.server;
/*========================================================================+
 |   Copyright (c) 2001, 2020 Oracle Corporation, Redwood Shores, CA, USA |
 |                      All rights reserved.                              |
 +========================================================================+
 |  HISTORY                                                               |
 | 5-Nov-2014 SRSIDDAM Created.                                           |
 +========================================================================+
 */
import oracle.apps.fnd.common.VersionInfo;
import oracle.apps.fnd.framework.server.OAEntityImpl;


import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FwkTbxNewEmpAddressEOImpl
  extends OAEntityImpl {
	  public static final String RCS_ID = "$Header: FwkTbxNewEmpAddressEOImpl.java 120.0.12020000.1 2020/01/08 05:32:28 spunam noship $"; 
    public static final boolean RCS_ID_RECORDED = VersionInfo.recordClassVersion(RCS_ID, "oracle.apps.fnd.framework.toolbox.tutorial2.server"); 
    public static final int ADDRESSID = 0;
    public static final int EMPLOYEEID = 1;
    public static final int DESKNUMBER = 2;
    public static final int MOBILENUMBER = 3;
    public static final int TELEPHONENUMBER = 4;
    public static final int FWKTBXNEWEMPLOYEEEO = 5;
    private static FwkTbxNewEmpAddressEODefImpl mDefinitionObject;

  /**This is the default constructor (do not remove)
   */
  public FwkTbxNewEmpAddressEOImpl()
  {
  }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = (FwkTbxNewEmpAddressEODefImpl)EntityDefImpl.findDefObject("oracle.apps.fnd.framework.toolbox.tutorial2.server.FwkTbxNewEmpAddressEO");
        }
        return mDefinitionObject;
    }

    /**Gets the attribute value for AddressId, using the alias name AddressId
     */
  public Number getAddressId()
  {
    return (Number) getAttributeInternal(ADDRESSID);
  }

  /**Sets <code>value</code> as the attribute value for AddressId
   */
  public void setAddressId(Number value)
  {
    setAttributeInternal(ADDRESSID, value);
  }

  /**Gets the attribute value for EmployeeId, using the alias name EmployeeId
   */
  public Number getEmployeeId()
  {
    return (Number) getAttributeInternal(EMPLOYEEID);
  }

  /**Sets <code>value</code> as the attribute value for EmployeeId
   */
  public void setEmployeeId(Number value)
  {
    setAttributeInternal(EMPLOYEEID, value);
  }

  public void setCreationDate(Date creationDate)
  {
    String a = null;
  }

  public void setCreatedBy(Number createdBy)
  {
    String a = null;
  }

  public void setLastUpdateDate(Date lastUpdateDate)
  {
    String a = null;
  }

  public void setLastUpdatedBy(Number lastUpdatedBy)
  {
    String a = null;
  }

  public void setLastUpdateLogin(Number lastUpdateLogin)
  {
    String a = null;
  }

  /**getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index,
                                         AttributeDefImpl attrDef)
    throws Exception
  {
        switch (index) {
        case ADDRESSID:
            return getAddressId();
        case EMPLOYEEID:
            return getEmployeeId();
        case DESKNUMBER:
            return getDeskNumber();
        case MOBILENUMBER:
            return getMobileNumber();
        case TELEPHONENUMBER:
            return getTelephoneNumber();
        case FWKTBXNEWEMPLOYEEEO:
            return getFwkTbxNewEMployeeEO();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

  /**setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value,
                                       AttributeDefImpl attrDef)
    throws Exception
  {
        switch (index) {
        case ADDRESSID:
            setAddressId((Number)value);
            return;
        case EMPLOYEEID:
            setEmployeeId((Number)value);
            return;
        case DESKNUMBER:
            setDeskNumber((String)value);
            return;
        case MOBILENUMBER:
            setMobileNumber((String)value);
            return;
        case TELEPHONENUMBER:
            setTelephoneNumber((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

  /**Gets the associated entity FwkTbxNewEMployeeEOImpl
   */
  public FwkTbxNewEMployeeEOImpl getFwkTbxNewEMployeeEO()
  {
    return (FwkTbxNewEMployeeEOImpl) getAttributeInternal(FWKTBXNEWEMPLOYEEEO);
  }

  /**Sets <code>value</code> as the associated entity FwkTbxNewEMployeeEOImpl
   */
  public void setFwkTbxNewEMployeeEO(FwkTbxNewEMployeeEOImpl value)
  {
    setAttributeInternal(FWKTBXNEWEMPLOYEEEO, value);
  }

    /**Gets the attribute value for DeskNumber, using the alias name DeskNumber
     */
    public String getDeskNumber() {
        return (String)getAttributeInternal(DESKNUMBER);
    }

    /**Sets <code>value</code> as the attribute value for DeskNumber
     */
    public void setDeskNumber(String value) {
        setAttributeInternal(DESKNUMBER, value);
    }

    /**Gets the attribute value for MobileNumber, using the alias name MobileNumber
     */
    public String getMobileNumber() {
        return (String)getAttributeInternal(MOBILENUMBER);
    }

    /**Sets <code>value</code> as the attribute value for MobileNumber
     */
    public void setMobileNumber(String value) {
        setAttributeInternal(MOBILENUMBER, value);
    }

    /**Gets the attribute value for TelephoneNumber, using the alias name TelephoneNumber
     */
    public String getTelephoneNumber() {
        return (String)getAttributeInternal(TELEPHONENUMBER);
    }

    /**Sets <code>value</code> as the attribute value for TelephoneNumber
     */
    public void setTelephoneNumber(String value) {
        setAttributeInternal(TELEPHONENUMBER, value);
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(Number addressId, Number employeeId) {
        return new Key(new Object[]{addressId, employeeId});
    }
}
