package oracle.apps.fnd.framework.toolbox.tutorial2.server;
/*========================================================================+
 |   Copyright (c) 2001, 2020 Oracle Corporation, Redwood Shores, CA, USA |
 |                      All rights reserved.                              |
 +========================================================================+
 |  HISTORY                                                               |
 | 5-Nov-2014 SRSIDDAM Created.                                           |
 +========================================================================+
 */
import oracle.apps.fnd.common.VersionInfo;
import oracle.apps.fnd.framework.server.OAEntityImpl;

import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FwkTbxNewExperienceEOImpl extends OAEntityImpl {
    public static final int EXPERIENCEID = 0;
    public static final int EMPLOYEEID = 1;
    public static final int ORGANIZATIONNAME = 2;
    public static final int DESIGNATION = 3;
    public static final int STARTDATE = 4;
    public static final int ENDDATE = 5;
    public static final int FWKTBXNEWEMPLOYEEEO = 6;
    private static FwkTbxNewExperienceEODefImpl mDefinitionObject;
    public static final String RCS_ID = "$Header: FwkTbxNewExperienceEOImpl.java 120.0.12020000.1 2020/01/08 06:49:27 spunam noship $"; 
    public static final boolean RCS_ID_RECORDED = VersionInfo.recordClassVersion(RCS_ID, "oracle.apps.fnd.framework.toolbox.tutorial2.server");

    /**This is the default constructor (do not remove)
     */
    public FwkTbxNewExperienceEOImpl() {
    }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = (FwkTbxNewExperienceEODefImpl)EntityDefImpl.findDefObject("oracle.apps.fnd.framework.toolbox.tutorial2.server.FwkTbxNewExperienceEO");
        }
        return mDefinitionObject;
    }

    /**Gets the attribute value for ExperienceId, using the alias name ExperienceId
     */
    public Number getExperienceId() {
        return (Number)getAttributeInternal(EXPERIENCEID);
    }

    /**Sets <code>value</code> as the attribute value for ExperienceId
     */
    public void setExperienceId(Number value) {
        setAttributeInternal(EXPERIENCEID, value);
    }

    /**Gets the attribute value for EmployeeId, using the alias name EmployeeId
     */
    public Number getEmployeeId() {
        return (Number)getAttributeInternal(EMPLOYEEID);
    }

    /**Sets <code>value</code> as the attribute value for EmployeeId
     */
    public void setEmployeeId(Number value) {
        setAttributeInternal(EMPLOYEEID, value);
    }

    /**Gets the attribute value for OrganizationName, using the alias name OrganizationName
     */
    public String getOrganizationName() {
        return (String)getAttributeInternal(ORGANIZATIONNAME);
    }

    /**Sets <code>value</code> as the attribute value for OrganizationName
     */
    public void setOrganizationName(String value) {
        setAttributeInternal(ORGANIZATIONNAME, value);
    }

    /**Gets the attribute value for Designation, using the alias name Designation
     */
    public String getDesignation() {
        return (String)getAttributeInternal(DESIGNATION);
    }

    /**Sets <code>value</code> as the attribute value for Designation
     */
    public void setDesignation(String value) {
        setAttributeInternal(DESIGNATION, value);
    }

    /**Gets the attribute value for StartDate, using the alias name StartDate
     */
    public Date getStartDate() {
        return (Date)getAttributeInternal(STARTDATE);
    }

    /**Sets <code>value</code> as the attribute value for StartDate
     */
    public void setStartDate(Date value) {
        setAttributeInternal(STARTDATE, value);
    }

    /**Gets the attribute value for EndDate, using the alias name EndDate
     */
    public Date getEndDate() {
        return (Date)getAttributeInternal(ENDDATE);
    }

    /**Sets <code>value</code> as the attribute value for EndDate
     */
    public void setEndDate(Date value) {
        setAttributeInternal(ENDDATE, value);
    }
    
    /**Adding setters for who columns
     * */
     public void setLastUpdatedBy(Number lastUpdatedBy){
         
     }
     public void setLastUpdateDate(Date lastUpdateDate){
         
     }
     public void setLastUpdateLogin(Number lastUpdateLogin){
         
     }
     public void setCreationDate(Date creationDate){
         
     }
     public void setCreatedBy(Number createdBy){
         
     }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case EXPERIENCEID:
            return getExperienceId();
        case EMPLOYEEID:
            return getEmployeeId();
        case ORGANIZATIONNAME:
            return getOrganizationName();
        case DESIGNATION:
            return getDesignation();
        case STARTDATE:
            return getStartDate();
        case ENDDATE:
            return getEndDate();
        case FWKTBXNEWEMPLOYEEEO:
            return getFwkTbxNewEMployeeEO();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case EXPERIENCEID:
            setExperienceId((Number)value);
            return;
        case EMPLOYEEID:
            setEmployeeId((Number)value);
            return;
        case ORGANIZATIONNAME:
            setOrganizationName((String)value);
            return;
        case DESIGNATION:
            setDesignation((String)value);
            return;
        case STARTDATE:
            setStartDate((Date)value);
            return;
        case ENDDATE:
            setEndDate((Date)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the associated entity oracle.apps.fnd.framework.toolbox.tutorial2.server.FwkTbxNewEMployeeEOImpl
     */
    public FwkTbxNewEMployeeEOImpl getFwkTbxNewEMployeeEO() {
        return (FwkTbxNewEMployeeEOImpl)getAttributeInternal(FWKTBXNEWEMPLOYEEEO);
    }

    /**Sets <code>value</code> as the associated entity oracle.apps.fnd.framework.toolbox.tutorial2.server.FwkTbxNewEMployeeEOImpl
     */
    public void setFwkTbxNewEMployeeEO(FwkTbxNewEMployeeEOImpl value) {
        setAttributeInternal(FWKTBXNEWEMPLOYEEEO, value);
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(Number experienceId) {
        return new Key(new Object[]{experienceId});
    }
}
