/*===========================================================================+
 | Copyright (c) 2012, 2020 Oracle Corporation, Redwood Shores, CA, USA |
 | All rights reserved. |
 +===========================================================================+
 | HISTORY |
 | 14-Aug-19 richanan Created. |
 |===========================================================================*/

package oracle.apps.fnd.framework.toolbox.tutorial2.server;

import oracle.apps.fnd.common.VersionInfo;
import oracle.apps.fnd.framework.server.OAEntityDefImpl;
import oracle.apps.fnd.framework.server.OAEntityImpl;

import oracle.apps.fnd.framework.server.OAViewRowImpl;


import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------

public class FwkTbxNewSkillsEOImpl
  extends OAEntityImpl {
    public static final int SKILLID = 0;
    public static final String RCS_ID = "$Header: FwkTbxNewSkillsEOImpl.java 120.0.12020000.1 2020/01/08 07:34:25 spunam noship $";
  public static final boolean RCS_ID_RECORDED =
    VersionInfo.recordClassVersion(RCS_ID,
                                   "oracle.apps.fnd.framework.toolbox.tutorial2.server");
    public static final int SKILLNAME = 1;
    public static final int VERSION = 2;
    public static final int BROADCATEGORY = 3;
    public static final int SKILLCATEGORY = 4;
    public static final int FWKTBXNEWEMPSKILLSEO = 5;
    public static final int FWKTBXNEWEMPSKILLSEO1 = 6;
    public static final int FWKTBXNEWEMPSKILLSVO = 7;


    private static OAEntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
  public FwkTbxNewSkillsEOImpl()
  {
  }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject =
                    (OAEntityDefImpl)EntityDefImpl.findDefObject("oracle.apps.fnd.framework.toolbox.tutorial2.server.FwkTbxNewSkillsEO");
        }
        return mDefinitionObject;
    }

    /**Gets the attribute value for SkillId, using the alias name SkillId
     */
  public Number getSkillId()
  {
    return (Number) getAttributeInternal(SKILLID);
  }

  /**Sets <code>value</code> as the attribute value for SkillId
   */
  public void setSkillId(Number value)
  {
    setAttributeInternal(SKILLID, value);
  }

  /**Gets the attribute value for SkillName, using the alias name SkillName
   */
  public String getSkillName()
  {
    return (String) getAttributeInternal(SKILLNAME);
  }

  /**Sets <code>value</code> as the attribute value for SkillName
   */
  public void setSkillName(String value)
  {
    setAttributeInternal(SKILLNAME, value);
  }

  /**Gets the attribute value for Version, using the alias name Version
   */
  public String getVersion()
  {
    return (String) getAttributeInternal(VERSION);
  }

  /**Sets <code>value</code> as the attribute value for Version
   */
  public void setVersion(String value)
  {
    setAttributeInternal(VERSION, value);
  }

  /**Gets the attribute value for BroadCategory, using the alias name BroadCategory
   */
  public String getBroadCategory()
  {
    return (String) getAttributeInternal(BROADCATEGORY);
  }

  /**Sets <code>value</code> as the attribute value for BroadCategory
   */
  public void setBroadCategory(String value)
  {
    setAttributeInternal(BROADCATEGORY, value);
  }

  /**Gets the attribute value for SkillCategory, using the alias name SkillCategory
   */
  public String getSkillCategory()
  {
    return (String) getAttributeInternal(SKILLCATEGORY);
  }

  /**Sets <code>value</code> as the attribute value for SkillCategory
   */
  public void setSkillCategory(String value)
  {
    setAttributeInternal(SKILLCATEGORY, value);
  }

  /**getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index,
                                         AttributeDefImpl attrDef)
    throws Exception
  {
        switch (index) {
        case SKILLID:
            return getSkillId();
        case SKILLNAME:
            return getSkillName();
        case VERSION:
            return getVersion();
        case BROADCATEGORY:
            return getBroadCategory();
        case SKILLCATEGORY:
            return getSkillCategory();
        case FWKTBXNEWEMPSKILLSEO:
            return getFwkTbxNewEmpSkillsEO();
        case FWKTBXNEWEMPSKILLSEO1:
            return getFwkTbxNewEmpSkillsEO1();
        case FWKTBXNEWEMPSKILLSVO:
            return getFwkTbxNewEmpSkillsVO();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

  /**setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value,
                                       AttributeDefImpl attrDef)
    throws Exception
  {
        switch (index) {
        case SKILLID:
            setSkillId((Number)value);
            return;
        case SKILLNAME:
            setSkillName((String)value);
            return;
        case VERSION:
            setVersion((String)value);
            return;
        case BROADCATEGORY:
            setBroadCategory((String)value);
            return;
        case SKILLCATEGORY:
            setSkillCategory((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

  /**Gets the associated entity oracle.jbo.RowIterator
   */
  public RowIterator getFwkTbxNewEmpSkillsEO()
  {
    return (RowIterator) getAttributeInternal(FWKTBXNEWEMPSKILLSEO);
  }


  public void setCreationDate(Date creationDate)
  {
  }

  public void setCreatedBy(Number createdBy)
  {
  }

  public void setLastUpdateDate(Date lastUpdateDate)
  {
  }

  public void setLastUpdatedBy(Number lastUpdatedBy)
  {
  }

  public void setLastUpdateLogin(Number lastUpdateLogin)
  {
  }


  /**Uses the link FwkTbxEmpSkillsVL to return rows of FwkTbxNewSkillsVO
   */
  public OAViewRowImpl getFwkTbxNewEmpSkillsVO()
  {
    return (OAViewRowImpl) getAttributeInternal(FWKTBXNEWEMPSKILLSVO);
  }

  /**Gets the associated entity FwkTbxNewEmpSkillsEOImpl
     */
    public FwkTbxNewEmpSkillsEOImpl getFwkTbxNewEmpSkillsEO1()
  {
    return (FwkTbxNewEmpSkillsEOImpl)getAttributeInternal(FWKTBXNEWEMPSKILLSEO1);
  }

  /**Sets <code>value</code> as the associated entity FwkTbxNewEmpSkillsEOImpl
   */
  public void setFwkTbxNewEmpSkillsEO1(FwkTbxNewEmpSkillsEOImpl value)
  {
    setAttributeInternal(FWKTBXNEWEMPSKILLSEO1, value);
  }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(Number skillId) {
        return new Key(new Object[]{skillId});
    }
}
