package oracle.apps.fnd.framework.toolbox.tutorial2.server;
/*========================================================================+
 |   Copyright (c) 2001, 2020 Oracle Corporation, Redwood Shores, CA, USA |
 |                      All rights reserved.                              |
 +========================================================================+
 |  HISTORY                                                               |
 | 5-Nov-2014 ychauhan  Created.                                           |
 +========================================================================+
 */
import oracle.apps.fnd.common.VersionInfo;
import oracle.apps.fnd.framework.server.OAViewRowImpl;


import oracle.jbo.Row;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FwkTbxNewEmployeeSearchVORowImpl
  extends OAViewRowImpl {
    public static final int EMPLOYEEID = 0;
    public static final int FIRSTNAME = 1;
  public static final int LASTNAME = 2;
  public static final int EMPLOYEEEMAIL = 4;
  public static final int POSITION = 5;
  public static final int SALARY = 6;
  public static final int STARTDATE = 7;
  public static final int ENDDATE = 8;
  public static final int MANAGEREMAIL = 10;
  public static final int FWKTBXNEWEMPLOYEESEARCHVO2 = 13;
  public static final int FWKTBXNEWEMPLOYEESEARCHVO = 14;
    public static final int EMAILADDRESS = 1;
    public static final int POSITIONCODE = 2;
    public static final int MANAGERNAME = 3;
    public static final int MANAGERID = 4;
    public static final int FULLNAME = 5;
    public static final int GUID = 6;
    public static final int MOBILENUMBER = 7;
    public static final int ADDRESSID = 8;
    public static final int EMPLOYEEID1 = 9;
    public static final int COUNTRY = 10;
    public static final int SELECTFLAG = 11;
    public static final String RCS_ID = "$Header: FwkTbxNewEmployeeSearchVORowImpl.java 120.0.12020000.1 2020/01/08 05:56:11 spunam noship $";
    public static final boolean RCS_ID_RECORDED = VersionInfo.recordClassVersion(RCS_ID, "oracle.apps.fnd.framework.toolbox.tutorial2.server");

    /**This is the default constructor (do not remove)
     */
  public FwkTbxNewEmployeeSearchVORowImpl()
  {
  }

  /**Gets FwkTbxNewEMployeeEO entity object.
   */
  public FwkTbxNewEMployeeEOImpl getFwkTbxNewEMployeeEO()
  {
    return (FwkTbxNewEMployeeEOImpl) getEntity(0);
  }

  /**Gets FwkTbxNewEMployeeEO1 entity object.
   */
  public FwkTbxNewEMployeeEOImpl getFwkTbxNewEMployeeEO1()
  {
    return (FwkTbxNewEMployeeEOImpl) getEntity(1);
  }

  /**Gets the attribute value for EMPLOYEE_ID using the alias name EmployeeId
   */
  public Number getEmployeeId()
  {
    return (Number) getAttributeInternal(EMPLOYEEID);
  }

  /**Sets <code>value</code> as attribute value for EMPLOYEE_ID using the alias name EmployeeId
   */
  public void setEmployeeId(Number value)
  {
    setAttributeInternal(EMPLOYEEID, value);
  }

  /**Gets the attribute value for FIRST_NAME using the alias name FirstName
   */
  public String getFirstName()
  {
    return (String) getAttributeInternal(FIRSTNAME);
  }

  /**Sets <code>value</code> as attribute value for FIRST_NAME using the alias name FirstName
   */
  public void setFirstName(String value)
  {
    setAttributeInternal(FIRSTNAME, value);
  }

  /**Gets the attribute value for LAST_NAME using the alias name LastName
   */
  public String getLastName()
  {
    return (String) getAttributeInternal(LASTNAME);
  }

  /**Sets <code>value</code> as attribute value for LAST_NAME using the alias name LastName
   */
  public void setLastName(String value)
  {
    setAttributeInternal(LASTNAME, value);
  }

  /**Gets the attribute value for FULL_NAME using the alias name FullName
   */
  public String getFullName()
  {
    return (String) getAttributeInternal(FULLNAME);
  }

  /**Sets <code>value</code> as attribute value for FULL_NAME using the alias name FullName
   */
  public void setFullName(String value)
  {
    setAttributeInternal(FULLNAME, value);
  }

  /**Gets the attribute value for EMAIL_ADDRESS using the alias name EmployeeEmail
   */
  public String getEmployeeEmail()
  {
    return (String) getAttributeInternal(EMPLOYEEEMAIL);
  }

  /**Sets <code>value</code> as attribute value for EMAIL_ADDRESS using the alias name EmployeeEmail
   */
  public void setEmployeeEmail(String value)
  {
    setAttributeInternal(EMPLOYEEEMAIL, value);
  }

  /**Gets the attribute value for POSITION_CODE using the alias name Position
   */
  public String getPosition()
  {
    return (String) getAttributeInternal(POSITION);
  }

  /**Sets <code>value</code> as attribute value for POSITION_CODE using the alias name Position
   */
  public void setPosition(String value)
  {
    setAttributeInternal(POSITION, value);
  }

  /**Gets the attribute value for SALARY using the alias name Salary
   */
  public Number getSalary()
  {
    return (Number) getAttributeInternal(SALARY);
  }

  /**Sets <code>value</code> as attribute value for SALARY using the alias name Salary
   */
  public void setSalary(Number value)
  {
    setAttributeInternal(SALARY, value);
  }

  /**Gets the attribute value for START_DATE using the alias name StartDate
   */
  public Date getStartDate()
  {
    return (Date) getAttributeInternal(STARTDATE);
  }

  /**Sets <code>value</code> as attribute value for START_DATE using the alias name StartDate
   */
  public void setStartDate(Date value)
  {
    setAttributeInternal(STARTDATE, value);
  }

  /**Gets the attribute value for END_DATE using the alias name EndDate
   */
  public Date getEndDate()
  {
    return (Date) getAttributeInternal(ENDDATE);
  }

  /**Sets <code>value</code> as attribute value for END_DATE using the alias name EndDate
   */
  public void setEndDate(Date value)
  {
    setAttributeInternal(ENDDATE, value);
  }

  /**Gets the attribute value for FULL_NAME using the alias name ManagerName
   */
  public String getManagerName()
  {
    return (String) getAttributeInternal(MANAGERNAME);
  }

  /**Gets the attribute value for EMAIL_ADDRESS using the alias name ManagerEmail
   */
  public String getManagerEmail()
  {
    return (String) getAttributeInternal(MANAGEREMAIL);
  }

  /**Gets the attribute value for EMPLOYEE_ID using the alias name ManagerId
   */
  public Number getManagerId()
  {
    return (Number) getAttributeInternal(MANAGERID);
  }

  /**getAttrInvokeAccessor: generated method. Do not modify.
   */
  protected Object getAttrInvokeAccessor(int index,
                                         AttributeDefImpl attrDef)
    throws Exception
  {
        switch (index) {
        case EMPLOYEEID:
            return getEmployeeId();
        case EMAILADDRESS:
            return getEmailAddress();
        case POSITIONCODE:
            return getPositionCode();
        case MANAGERNAME:
            return getManagerName();
        case MANAGERID:
            return getManagerId();
        case FULLNAME:
            return getFullName();
        case GUID:
            return getGuid();
        case MOBILENUMBER:
            return getMobileNumber();
        case ADDRESSID:
            return getAddressId();
        case EMPLOYEEID1:
            return getEmployeeId1();
        case COUNTRY:
            return getCountry();
        case SELECTFLAG:
            return getSelectFlag();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

  /**setAttrInvokeAccessor: generated method. Do not modify.
   */
  protected void setAttrInvokeAccessor(int index, Object value,
                                       AttributeDefImpl attrDef)
    throws Exception
  {
        switch (index) {
        case EMPLOYEEID:
            setEmployeeId((Number)value);
            return;
        case EMAILADDRESS:
            setEmailAddress((String)value);
            return;
        case POSITIONCODE:
            setPositionCode((String)value);
            return;
        case FULLNAME:
            setFullName((String)value);
            return;
        case GUID:
            setGuid((String)value);
            return;
        case MOBILENUMBER:
            setMobileNumber((String)value);
            return;
        case ADDRESSID:
            setAddressId((Number)value);
            return;
        case EMPLOYEEID1:
            setEmployeeId1((Number)value);
            return;
        case SELECTFLAG:
            setSelectFlag((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }


  /**Gets the associated <code>Row</code> using master-detail link FwkTbxNewEmployeeSearchVO2
   */
  public Row getFwkTbxNewEmployeeSearchVO2()
  {
    return (Row) getAttributeInternal(FWKTBXNEWEMPLOYEESEARCHVO2);
  }

  /**Gets the associated <code>RowIterator</code> using master-detail link FwkTbxNewEmployeeSearchVO
   */
  public RowIterator getFwkTbxNewEmployeeSearchVO()
  {
    return (RowIterator) getAttributeInternal(FWKTBXNEWEMPLOYEESEARCHVO);
  }

  /**Gets the attribute value for EMAIL_ADDRESS using the alias name EmailAddress
   */
  public String getEmailAddress()
  {
    return (String) getAttributeInternal(EMAILADDRESS);
  }

  /**Sets <code>value</code> as attribute value for EMAIL_ADDRESS using the alias name EmailAddress
   */
  public void setEmailAddress(String value)
  {
    setAttributeInternal(EMAILADDRESS, value);
  }

  /**Gets the attribute value for POSITION_CODE using the alias name PositionCode
   */
  public String getPositionCode()
  {
    return (String) getAttributeInternal(POSITIONCODE);
  }

  /**Sets <code>value</code> as attribute value for POSITION_CODE using the alias name PositionCode
   */
  public void setPositionCode(String value)
  {
    setAttributeInternal(POSITIONCODE, value);
  }


  /**Gets FwkTbxNewEmpAddressEO entity object.
     */
    public FwkTbxNewEmpAddressEOImpl getFwkTbxNewEmpAddressEO()
  {
    return (FwkTbxNewEmpAddressEOImpl)getEntity(2);
  }

  /**Gets the attribute value for GUID using the alias name Guid
   */
  public String getGuid()
  {
    return (String) getAttributeInternal(GUID);
  }

  /**Sets <code>value</code> as attribute value for GUID using the alias name Guid
   */
  public void setGuid(String value)
  {
    setAttributeInternal(GUID, value);
  }

  /**Gets the attribute value for MOBILE_NUMBER using the alias name MobileNumber
   */
  public String getMobileNumber()
  {
    return (String) getAttributeInternal(MOBILENUMBER);
  }

  /**Sets <code>value</code> as attribute value for MOBILE_NUMBER using the alias name MobileNumber
   */
  public void setMobileNumber(String value)
  {
    setAttributeInternal(MOBILENUMBER, value);
  }

  /**Gets the attribute value for ADDRESS_ID using the alias name AddressId
   */
  public Number getAddressId()
  {
    return (Number) getAttributeInternal(ADDRESSID);
  }

  /**Sets <code>value</code> as attribute value for ADDRESS_ID using the alias name AddressId
   */
  public void setAddressId(Number value)
  {
    setAttributeInternal(ADDRESSID, value);
  }

  /**Gets the attribute value for EMPLOYEE_ID using the alias name EmployeeId1
   */
  public Number getEmployeeId1()
  {
    return (Number) getAttributeInternal(EMPLOYEEID1);
  }

  /**Sets <code>value</code> as attribute value for EMPLOYEE_ID using the alias name EmployeeId1
   */
  public void setEmployeeId1(Number value)
  {
    setAttributeInternal(EMPLOYEEID1, value);
  }

  /**Gets the attribute value for the calculated attribute Country
   */
  public String getCountry()
  {
    return (String) getAttributeInternal(COUNTRY);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute Country
   */
  public void setCountry(String value)
  {
    setAttributeInternal(COUNTRY, value);
  }

  /**Gets the attribute value for the calculated attribute SelectFlag
   */
  public String getSelectFlag()
  {
    if (getAttributeInternal(SELECTFLAG) == null)
    {
      return "N";
    }
    return (String) getAttributeInternal(SELECTFLAG);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute SelectFlag
   */
  public void setSelectFlag(String value)
  {
    populateAttribute(SELECTFLAG, value);
  }
}
