package oracle.apps.fnd.framework.toolbox.tutorial2.server;
/*========================================================================+
 |   Copyright (c) 2001, 2020 Oracle Corporation, Redwood Shores, CA, USA |
 |                      All rights reserved.                              |
 +========================================================================+
 |  HISTORY                                                               |
 | 5-Nov-2014 SRSIDDAM Created.                                           |
 +========================================================================+
 */
import oracle.apps.fnd.common.VersionInfo;
import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FwkTbxNewEmpSkillsDetVORowImpl extends OAViewRowImpl {
    public static final int SKILLID = 0;
    public static final int EMPLOYEEID = 1;
    public static final int SKILLNAME = 2;
    public static final int SKILLRATING = 3;
    public static final int PROFICIENCY = 4;
    public static final int VERSION = 5;
    public static final int BROADCATEGORY = 6;
    public static final int SKILLCATEGORY = 7;
    public static final String RCS_ID = "$Header: FwkTbxNewEmpSkillsDetVORowImpl.java 120.0.12020000.1 2020/01/08 06:04:43 spunam noship $";
    public static final boolean RCS_ID_RECORDED = VersionInfo.recordClassVersion(RCS_ID, "oracle.apps.fnd.framework.toolbox.tutorial2.server"); 

    /**This is the default constructor (do not remove)
     */
    public FwkTbxNewEmpSkillsDetVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute SkillId
     */
    public Number getSkillId() {
        return (Number) getAttributeInternal(SKILLID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SkillId
     */
    public void setSkillId(Number value) {
        setAttributeInternal(SKILLID, value);
    }

    /**Gets the attribute value for the calculated attribute EmployeeId
     */
    public Number getEmployeeId() {
        return (Number) getAttributeInternal(EMPLOYEEID);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute EmployeeId
     */
    public void setEmployeeId(Number value) {
        setAttributeInternal(EMPLOYEEID, value);
    }

    /**Gets the attribute value for the calculated attribute SkillName
     */
    public String getSkillName() {
        return (String) getAttributeInternal(SKILLNAME);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SkillName
     */
    public void setSkillName(String value) {
        setAttributeInternal(SKILLNAME, value);
    }

    /**Gets the attribute value for the calculated attribute SkillRating
     */
    public Number getSkillRating() {
        return (Number) getAttributeInternal(SKILLRATING);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SkillRating
     */
    public void setSkillRating(Number value) {
        setAttributeInternal(SKILLRATING, value);
    }

    /**Gets the attribute value for the calculated attribute Proficiency
     */
    public String getProficiency() {
        return (String) getAttributeInternal(PROFICIENCY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Proficiency
     */
    public void setProficiency(String value) {
        setAttributeInternal(PROFICIENCY, value);
    }

    /**Gets the attribute value for the calculated attribute Version
     */
    public String getVersion() {
        return (String) getAttributeInternal(VERSION);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Version
     */
    public void setVersion(String value) {
        setAttributeInternal(VERSION, value);
    }

    /**Gets the attribute value for the calculated attribute BroadCategory
     */
    public String getBroadCategory() {
        return (String) getAttributeInternal(BROADCATEGORY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute BroadCategory
     */
    public void setBroadCategory(String value) {
        setAttributeInternal(BROADCATEGORY, value);
    }

    /**Gets the attribute value for the calculated attribute SkillCategory
     */
    public String getSkillCategory() {
        return (String) getAttributeInternal(SKILLCATEGORY);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute SkillCategory
     */
    public void setSkillCategory(String value) {
        setAttributeInternal(SKILLCATEGORY, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case SKILLID:
            return getSkillId();
        case EMPLOYEEID:
            return getEmployeeId();
        case SKILLNAME:
            return getSkillName();
        case SKILLRATING:
            return getSkillRating();
        case PROFICIENCY:
            return getProficiency();
        case VERSION:
            return getVersion();
        case BROADCATEGORY:
            return getBroadCategory();
        case SKILLCATEGORY:
            return getSkillCategory();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case SKILLID:
            setSkillId((Number)value);
            return;
        case EMPLOYEEID:
            setEmployeeId((Number)value);
            return;
        case SKILLNAME:
            setSkillName((String)value);
            return;
        case SKILLRATING:
            setSkillRating((Number)value);
            return;
        case PROFICIENCY:
            setProficiency((String)value);
            return;
        case VERSION:
            setVersion((String)value);
            return;
        case BROADCATEGORY:
            setBroadCategory((String)value);
            return;
        case SKILLCATEGORY:
            setSkillCategory((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
