/*========================================================================+
 |   Copyright (c) 2001, 2020 Oracle Corporation, Redwood Shores, CA, USA |
 |                      All rights reserved.                              |
 +========================================================================+
 |  HISTORY                                                               |
 | 5-Nov-2014 SRSIDDAM Created.                                           |
 +========================================================================+
 */
package oracle.apps.fnd.framework.toolbox.tutorial2.server;

import oracle.apps.fnd.common.VersionInfo;
import oracle.apps.fnd.framework.server.OAEntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FwkTbxNewEmpTrainingsEODefImpl extends OAEntityDefImpl {
    public static final String RCS_ID = "$Header: FwkTbxNewEmpTrainingsEODefImpl.java 120.0.12020000.1 2020/01/08 06:29:07 spunam noship $"; 
    public static final boolean RCS_ID_RECORDED = VersionInfo.recordClassVersion(RCS_ID, "oracle.apps.fnd.framework.toolbox.tutorial2.server"); 
    /**This is the default constructor (do not remove)
     */
    public FwkTbxNewEmpTrainingsEODefImpl() {
    }
}
