package oracle.apps.fnd.framework.toolbox.tutorial2.server;
/*===========================================================================+
 | Copyright (c) 2012, 2020 Oracle Corporation, Redwood Shores, CA, USA             |
 | All rights reserved.                                                       |
 +============================================================================+
 | HISTORY                                                                    |
 | 8/19/19 ychauhan created                                                   |
 |===========================================================================*/
import oracle.apps.fnd.common.VersionInfo;
import oracle.apps.fnd.framework.server.OAEntityDefImpl;
import oracle.apps.fnd.framework.server.OAEntityImpl;

import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FwkTbxNewTrainingEOImpl extends OAEntityImpl {
    public static final String RCS_ID = "$Header: FwkTbxNewTrainingEOImpl.java 120.0.12020000.1 2020/01/08 07:38:42 spunam noship $";
    public static final boolean RCS_ID_RECORDED = VersionInfo.recordClassVersion(RCS_ID, "oracle.apps.fnd.framework.toolbox.tutorial2.server");
    public static final int TRAININGID = 0;
    public static final int TRAININGNAME = 1;
    public static final int TRAININGDESCRIPTION = 2;
    public static final int MANDATORY = 3;
    public static final int TRAININGSTARTDATE = 4;
    public static final int TRAININGENDDATE = 5;
    public static final int INSTRUCTOR = 6;
    public static final int DURATIONINMIN = 7;
    public static final int FWKTBXNEWEMPTRAININGSEO = 8;


    private static OAEntityDefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public FwkTbxNewTrainingEOImpl() {
    }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject =
                    (OAEntityDefImpl)EntityDefImpl.findDefObject("oracle.apps.fnd.framework.toolbox.tutorial2.server.FwkTbxNewTrainingEO");
        }
        return mDefinitionObject;
    }

    /**Gets the attribute value for TrainingId, using the alias name TrainingId
     */
    public Number getTrainingId() {
        return (Number)getAttributeInternal(TRAININGID);
    }

    /**Sets <code>value</code> as the attribute value for TrainingId
     */
    public void setTrainingId(Number value) {
        setAttributeInternal(TRAININGID, value);
    }

    /**Gets the attribute value for TrainingName, using the alias name TrainingName
     */
    public String getTrainingName() {
        return (String)getAttributeInternal(TRAININGNAME);
    }

    /**Sets <code>value</code> as the attribute value for TrainingName
     */
    public void setTrainingName(String value) {
        setAttributeInternal(TRAININGNAME, value);
    }

    /**Gets the attribute value for TrainingDescription, using the alias name TrainingDescription
     */
    public String getTrainingDescription() {
        return (String)getAttributeInternal(TRAININGDESCRIPTION);
    }

    /**Sets <code>value</code> as the attribute value for TrainingDescription
     */
    public void setTrainingDescription(String value) {
        setAttributeInternal(TRAININGDESCRIPTION, value);
    }

    /**Gets the attribute value for Mandatory, using the alias name Mandatory
     */
    public String getMandatory() {
        return (String)getAttributeInternal(MANDATORY);
    }

    /**Sets <code>value</code> as the attribute value for Mandatory
     */
    public void setMandatory(String value) {
        setAttributeInternal(MANDATORY, value);
    }

    /**Gets the attribute value for TrainingStartDate, using the alias name TrainingStartDate
     */
    public Date getTrainingStartDate() {
        return (Date)getAttributeInternal(TRAININGSTARTDATE);
    }

    /**Sets <code>value</code> as the attribute value for TrainingStartDate
     */
    public void setTrainingStartDate(Date value) {
        setAttributeInternal(TRAININGSTARTDATE, value);
    }

    /**Gets the attribute value for TrainingEndDate, using the alias name TrainingEndDate
     */
    public Date getTrainingEndDate() {
        return (Date)getAttributeInternal(TRAININGENDDATE);
    }

    /**Sets <code>value</code> as the attribute value for TrainingEndDate
     */
    public void setTrainingEndDate(Date value) {
        setAttributeInternal(TRAININGENDDATE, value);
    }

    /**Gets the attribute value for Instructor, using the alias name Instructor
     */
    public String getInstructor() {
        return (String)getAttributeInternal(INSTRUCTOR);
    }

    /**Sets <code>value</code> as the attribute value for Instructor
     */
    public void setInstructor(String value) {
        setAttributeInternal(INSTRUCTOR, value);
    }

    /**Gets the attribute value for DurationInMin, using the alias name DurationInMin
     */
    public Number getDurationInMin() {
        return (Number)getAttributeInternal(DURATIONINMIN);
    }

    /**Sets <code>value</code> as the attribute value for DurationInMin
     */
    public void setDurationInMin(Number value) {
        setAttributeInternal(DURATIONINMIN, value);
    }
    
    /**Adding setters for who columns
     * */
     public void setLastUpdatedBy(Number lastUpdatedBy){
         
     }
     public void setLastUpdateDate(Date lastUpdateDate){
         
     }
     public void setLastUpdateLogin(Number lastUpdateLogin){
         
     }
     public void setCreationDate(Date creationDate){
         
     }
     public void setCreatedBy(Number createdBy){
         
     }
    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case TRAININGID:
            return getTrainingId();
        case TRAININGNAME:
            return getTrainingName();
        case TRAININGDESCRIPTION:
            return getTrainingDescription();
        case MANDATORY:
            return getMandatory();
        case TRAININGSTARTDATE:
            return getTrainingStartDate();
        case TRAININGENDDATE:
            return getTrainingEndDate();
        case INSTRUCTOR:
            return getInstructor();
        case DURATIONINMIN:
            return getDurationInMin();
        case FWKTBXNEWEMPTRAININGSEO:
            return getFwkTbxNewEmpTrainingsEO();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case TRAININGID:
            setTrainingId((Number)value);
            return;
        case TRAININGNAME:
            setTrainingName((String)value);
            return;
        case TRAININGDESCRIPTION:
            setTrainingDescription((String)value);
            return;
        case MANDATORY:
            setMandatory((String)value);
            return;
        case TRAININGSTARTDATE:
            setTrainingStartDate((Date)value);
            return;
        case TRAININGENDDATE:
            setTrainingEndDate((Date)value);
            return;
        case INSTRUCTOR:
            setInstructor((String)value);
            return;
        case DURATIONINMIN:
            setDurationInMin((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the associated entity oracle.jbo.RowIterator
     */
    public RowIterator getFwkTbxNewEmpTrainingsEO() {
        return (RowIterator)getAttributeInternal(FWKTBXNEWEMPTRAININGSEO);
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(Number trainingId) {
        return new Key(new Object[]{trainingId});
    }
}
