package oracle.apps.fnd.framework.toolbox.tutorial2.server;
/*========================================================================+
 |   Copyright (c) 2001, 2020 Oracle Corporation, Redwood Shores, CA, USA |
 |                      All rights reserved.                              |
 +========================================================================+
 |  HISTORY                                                               |
 | 5-Nov-2014 SRSIDDAM Created.                                           |
 +========================================================================*/
import oracle.apps.fnd.common.VersionInfo;
import oracle.apps.fnd.framework.server.OAEntityImpl;

import oracle.jbo.Key;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FwkTbxNewEducationEOImpl extends OAEntityImpl {
    public static final int EDUCATIONID = 0;
    public static final int EMPLOYEEID = 1;
    public static final int EDUCATIONNAME = 2;
    public static final int EDUCATIONSPECIALIZATION = 3;
    public static final int COMPLETIONYEAR = 4;
    public static final int UNIVERSITYNAME = 5;
    public static final int STARTDATE = 6;
    public static final int ENDDATE = 7;
    public static final int FWKTBXNEWEMPLOYEEEO = 8;
    private static FwkTbxNewEducationEODefImpl mDefinitionObject;
	  public static final String RCS_ID = "$Header: FwkTbxNewEducationEOImpl.java 120.0.12020000.1 2020/01/08 05:19:47 spunam noship $";
    public static final boolean RCS_ID_RECORDED = VersionInfo.recordClassVersion(RCS_ID, "oracle.apps.fnd.framework.toolbox.tutorial2.server");
    /**This is the default constructor (do not remove)
     */
    public FwkTbxNewEducationEOImpl() {
    }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = (FwkTbxNewEducationEODefImpl)EntityDefImpl.findDefObject("oracle.apps.fnd.framework.toolbox.tutorial2.server.FwkTbxNewEducationEO");
        }
        return mDefinitionObject;
    }

    /**Gets the attribute value for EducationId, using the alias name EducationId
     */
    public Number getEducationId() {
        return (Number)getAttributeInternal(EDUCATIONID);
    }

    /**Sets <code>value</code> as the attribute value for EducationId
     */
    public void setEducationId(Number value) {
        setAttributeInternal(EDUCATIONID, value);
    }

    /**Gets the attribute value for EmployeeId, using the alias name EmployeeId
     */
    public Number getEmployeeId() {
        return (Number)getAttributeInternal(EMPLOYEEID);
    }

    /**Sets <code>value</code> as the attribute value for EmployeeId
     */
    public void setEmployeeId(Number value) {
        setAttributeInternal(EMPLOYEEID, value);
    }

    /**Gets the attribute value for EducationName, using the alias name EducationName
     */
    public String getEducationName() {
        return (String)getAttributeInternal(EDUCATIONNAME);
    }

    /**Sets <code>value</code> as the attribute value for EducationName
     */
    public void setEducationName(String value) {
        setAttributeInternal(EDUCATIONNAME, value);
    }

    /**Gets the attribute value for EducationSpecialization, using the alias name EducationSpecialization
     */
    public String getEducationSpecialization() {
        return (String)getAttributeInternal(EDUCATIONSPECIALIZATION);
    }

    /**Sets <code>value</code> as the attribute value for EducationSpecialization
     */
    public void setEducationSpecialization(String value) {
        setAttributeInternal(EDUCATIONSPECIALIZATION, value);
    }

    /**Gets the attribute value for CompletionYear, using the alias name CompletionYear
     */
    public Date getCompletionYear() {
        return (Date)getAttributeInternal(COMPLETIONYEAR);
    }

    /**Sets <code>value</code> as the attribute value for CompletionYear
     */
    public void setCompletionYear(Date value) {
        setAttributeInternal(COMPLETIONYEAR, value);
    }

    /**Gets the attribute value for UniversityName, using the alias name UniversityName
     */
    public String getUniversityName() {
        return (String)getAttributeInternal(UNIVERSITYNAME);
    }

    /**Sets <code>value</code> as the attribute value for UniversityName
     */
    public void setUniversityName(String value) {
        setAttributeInternal(UNIVERSITYNAME, value);
    }

    /**Gets the attribute value for StartDate, using the alias name StartDate
     */
    public Date getStartDate() {
        return (Date)getAttributeInternal(STARTDATE);
    }

    /**Sets <code>value</code> as the attribute value for StartDate
     */
    public void setStartDate(Date value) {
        setAttributeInternal(STARTDATE, value);
    }

    /**Gets the attribute value for EndDate, using the alias name EndDate
     */
    public Date getEndDate() {
        return (Date)getAttributeInternal(ENDDATE);
    }

    /**Sets <code>value</code> as the attribute value for EndDate
     */
    public void setEndDate(Date value) {
        setAttributeInternal(ENDDATE, value);
    }
    /**Adding who column setters
     * */
    public void setLastUpdateLogin(Number lastUpdateDate){
        
    }
    public void setLastUpdatedBy(Number lastUpdatedBy){
        
    }
    public void setLastUpdateDate(Date date){
        
    }
    public void setCreatedBy(Number createdBy){
        
    }
    public void setCreationDate(Date date){
        
    }
    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case EDUCATIONID:
            return getEducationId();
        case EMPLOYEEID:
            return getEmployeeId();
        case EDUCATIONNAME:
            return getEducationName();
        case EDUCATIONSPECIALIZATION:
            return getEducationSpecialization();
        case COMPLETIONYEAR:
            return getCompletionYear();
        case UNIVERSITYNAME:
            return getUniversityName();
        case STARTDATE:
            return getStartDate();
        case ENDDATE:
            return getEndDate();
        case FWKTBXNEWEMPLOYEEEO:
            return getFwkTbxNewEMployeeEO();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case EDUCATIONID:
            setEducationId((Number)value);
            return;
        case EMPLOYEEID:
            setEmployeeId((Number)value);
            return;
        case EDUCATIONNAME:
            setEducationName((String)value);
            return;
        case EDUCATIONSPECIALIZATION:
            setEducationSpecialization((String)value);
            return;
        case COMPLETIONYEAR:
            setCompletionYear((Date)value);
            return;
        case UNIVERSITYNAME:
            setUniversityName((String)value);
            return;
        case STARTDATE:
            setStartDate((Date)value);
            return;
        case ENDDATE:
            setEndDate((Date)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the associated entity oracle.apps.fnd.framework.toolbox.tutorial2.server.FwkTbxNewEMployeeEOImpl
     */
    public FwkTbxNewEMployeeEOImpl getFwkTbxNewEMployeeEO() {
        return (FwkTbxNewEMployeeEOImpl)getAttributeInternal(FWKTBXNEWEMPLOYEEEO);
    }

    /**Sets <code>value</code> as the associated entity oracle.apps.fnd.framework.toolbox.tutorial2.server.FwkTbxNewEMployeeEOImpl
     */
    public void setFwkTbxNewEMployeeEO(FwkTbxNewEMployeeEOImpl value) {
        setAttributeInternal(FWKTBXNEWEMPLOYEEEO, value);
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(Number educationId) {
        return new Key(new Object[]{educationId});
    }
}
