package oracle.apps.fnd.framework.toolbox.tutorial2.server;
/*========================================================================+
 |   Copyright (c) 2001, 2020 Oracle Corporation, Redwood Shores, CA, USA |
 |                      All rights reserved.                              |
 +========================================================================+
 |  HISTORY                                                               |
 | 5-Nov-2014 SRSIDDAM Created.                                           |
 +========================================================================+
 */
import oracle.apps.fnd.common.VersionInfo;
import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FwkTbxNewAssetVORowImpl extends OAViewRowImpl {
    public static final int ASSETID = 0;
    public static final String RCS_ID = "$Header: FwkTbxNewAssetVORowImpl.java 120.0.12020000.1 2020/01/08 05:12:59 spunam noship $"; 
  public static final boolean RCS_ID_RECORDED = VersionInfo.recordClassVersion(RCS_ID, "oracle.apps.fnd.framework.toolbox.tutorial2.server");
    public static final int EMPLOYEEID = 1;
    public static final int ASSETTYPE = 2;
    public static final int MODELNUMBER = 3;
    public static final int AVAILABLE = 4;
    public static final int INUSESINCE = 5;
    public static final int ASSETNUMBID = 6;
    public static final int ASSETNUMBSTRUCTUREID = 7;
    public static final int ASSETNUMBER = 8;
    public static final int CCID = 9;

    /**This is the default constructor (do not remove)
     */
    public FwkTbxNewAssetVORowImpl() {
    }

    /**Gets FwkTbxNewAssetEO entity object.
     */
    public FwkTbxNewAssetEOImpl getFwkTbxNewAssetEO() {
        return (FwkTbxNewAssetEOImpl)getEntity(0);
    }

    /**Gets the attribute value for ASSET_ID using the alias name AssetId
     */
    public Number getAssetId() {
        return (Number) getAttributeInternal(ASSETID);
    }

    /**Sets <code>value</code> as attribute value for ASSET_ID using the alias name AssetId
     */
    public void setAssetId(Number value) {
        setAttributeInternal(ASSETID, value);
    }

    /**Gets the attribute value for ASSET_TYPE using the alias name AssetType
     */
    public String getAssetType() {
        return (String) getAttributeInternal(ASSETTYPE);
    }

    /**Sets <code>value</code> as attribute value for ASSET_TYPE using the alias name AssetType
     */
    public void setAssetType(String value) {
        setAttributeInternal(ASSETTYPE, value);
    }

    /**Gets the attribute value for MODEL_NUMBER using the alias name ModelNumber
     */
    public String getModelNumber() {
        return (String) getAttributeInternal(MODELNUMBER);
    }

    /**Sets <code>value</code> as attribute value for MODEL_NUMBER using the alias name ModelNumber
     */
    public void setModelNumber(String value) {
        setAttributeInternal(MODELNUMBER, value);
    }

    /**Gets the attribute value for IN_USE_SINCE using the alias name InUseSince
     */
    public Date getInUseSince() {
        return (Date) getAttributeInternal(INUSESINCE);
    }

    /**Sets <code>value</code> as attribute value for IN_USE_SINCE using the alias name InUseSince
     */
    public void setInUseSince(Date value) {
        setAttributeInternal(INUSESINCE, value);
    }

    /**Gets the attribute value for ASSETNUMB_ID using the alias name AssetnumbId
     */
    public Number getAssetnumbId() {
        return (Number) getAttributeInternal(ASSETNUMBID);
    }

    /**Sets <code>value</code> as attribute value for ASSETNUMB_ID using the alias name AssetnumbId
     */
    public void setAssetnumbId(Number value) {
        setAttributeInternal(ASSETNUMBID, value);
    }

    /**Gets the attribute value for ASSETNUMB_STRUCTURE_ID using the alias name AssetnumbStructureId
     */
    public Number getAssetnumbStructureId() {
        return (Number) getAttributeInternal(ASSETNUMBSTRUCTUREID);
    }

    /**Sets <code>value</code> as attribute value for ASSETNUMB_STRUCTURE_ID using the alias name AssetnumbStructureId
     */
    public void setAssetnumbStructureId(Number value) {
        setAttributeInternal(ASSETNUMBSTRUCTUREID, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ASSETID:
            return getAssetId();
        case EMPLOYEEID:
            return getEmployeeId();
        case ASSETTYPE:
            return getAssetType();
        case MODELNUMBER:
            return getModelNumber();
        case AVAILABLE:
            return getAvailable();
        case INUSESINCE:
            return getInUseSince();
        case ASSETNUMBID:
            return getAssetnumbId();
        case ASSETNUMBSTRUCTUREID:
            return getAssetnumbStructureId();
        case ASSETNUMBER:
            return getAssetNumber();
        case CCID:
            return getCCID();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case ASSETID:
            setAssetId((Number)value);
            return;
        case EMPLOYEEID:
            setEmployeeId((Number)value);
            return;
        case ASSETTYPE:
            setAssetType((String)value);
            return;
        case MODELNUMBER:
            setModelNumber((String)value);
            return;
        case AVAILABLE:
            setAvailable((String)value);
            return;
        case INUSESINCE:
            setInUseSince((Date)value);
            return;
        case ASSETNUMBID:
            setAssetnumbId((Number)value);
            return;
        case ASSETNUMBSTRUCTUREID:
            setAssetnumbStructureId((Number)value);
            return;
        case ASSETNUMBER:
            setAssetNumber((String)value);
            return;
        case CCID:
            setCCID((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }


  /**Gets the attribute value for EMPLOYEE_ID using the alias name EmployeeId
   */
  public Number getEmployeeId()
  {
    return (Number) getAttributeInternal(EMPLOYEEID);
  }

  /**Sets <code>value</code> as attribute value for EMPLOYEE_ID using the alias name EmployeeId
   */
  public void setEmployeeId(Number value)
  {
    setAttributeInternal(EMPLOYEEID, value);
  }

  /**Gets the attribute value for AVAILABLE using the alias name Available
   */
  public String getAvailable()
  {
    return (String) getAttributeInternal(AVAILABLE);
  }

  /**Sets <code>value</code> as attribute value for AVAILABLE using the alias name Available
   */
  public void setAvailable(String value)
  {
    setAttributeInternal(AVAILABLE, value);
  }


  /**Gets the attribute value for the calculated attribute AssetNumber
   */
  public String getAssetNumber()
  {
    return (String) getAttributeInternal(ASSETNUMBER);
  }

  /**Sets <code>value</code> as the attribute value for the calculated attribute AssetNumber
   */
  public void setAssetNumber(String value)
  {
    setAttributeInternal(ASSETNUMBER, value);
  }

    /**Gets the attribute value for CCID using the alias name CCID
     */
    public Number getCCID() {
        return (Number) getAttributeInternal(CCID);
    }

    /**Sets <code>value</code> as attribute value for CCID using the alias name CCID
     */
    public void setCCID(Number value) {
        setAttributeInternal(CCID, value);
    }
}
