package oracle.apps.fnd.framework.toolbox.tutorial2.server;
/*========================================================================+
 |   Copyright (c) 2001, 2020 Oracle Corporation, Redwood Shores, CA, USA |
 |                      All rights reserved.                              |
 +========================================================================+
 |  HISTORY                                                               |
 | 5-Nov-2014 SRSIDDAM Created.                                           |
 +========================================================================+
 */
import oracle.apps.fnd.common.VersionInfo;
import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FwkTbxNewEmpTrendGraphVORowImpl extends OAViewRowImpl {
    public static final int TITLE = 0;
    public static final int YEAR = 1;
    public static final int TITLECOUNT = 2;
    public static final String RCS_ID = "$Header: FwkTbxNewEmpTrendGraphVORowImpl.java 120.0.12020000.1 2020/01/08 06:38:52 spunam noship $"; 
    public static final boolean RCS_ID_RECORDED = VersionInfo.recordClassVersion(RCS_ID, "oracle.apps.fnd.framework.toolbox.tutorial2.server");

    /**This is the default constructor (do not remove)
     */
    public FwkTbxNewEmpTrendGraphVORowImpl() {
    }

    /**Gets the attribute value for the calculated attribute Title
     */
    public String getTitle() {
        return (String) getAttributeInternal(TITLE);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Title
     */
    public void setTitle(String value) {
        setAttributeInternal(TITLE, value);
    }

    /**Gets the attribute value for the calculated attribute Year
     */
    public String getYear() {
        return (String) getAttributeInternal(YEAR);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute Year
     */
    public void setYear(String value) {
        setAttributeInternal(YEAR, value);
    }

    /**Gets the attribute value for the calculated attribute TitleCount
     */
    public Number getTitleCount() {
        return (Number) getAttributeInternal(TITLECOUNT);
    }

    /**Sets <code>value</code> as the attribute value for the calculated attribute TitleCount
     */
    public void setTitleCount(Number value) {
        setAttributeInternal(TITLECOUNT, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case TITLE:
            return getTitle();
        case YEAR:
            return getYear();
        case TITLECOUNT:
            return getTitleCount();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case TITLE:
            setTitle((String)value);
            return;
        case YEAR:
            setYear((String)value);
            return;
        case TITLECOUNT:
            setTitleCount((Number)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
