package oracle.apps.fnd.framework.toolbox.tutorial2.server;
/*========================================================================+
 |   Copyright (c) 2001, 2020 Oracle Corporation, Redwood Shores, CA, USA |
 |                      All rights reserved.                              |
 +========================================================================+
 |  HISTORY                                                               |
 | 5-Nov-2014 SRSIDDAM Created.                                           |
 +========================================================================*/

import oracle.apps.fnd.common.VersionInfo;

import oracle.jbo.server.ViewDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FwkTbxNewSkillsVODefImpl extends ViewDefImpl {
    public static final String RCS_ID = "$Header: FwkTbxNewSkillsVODefImpl.java 120.0.12020000.1 2020/01/08 07:36:00 spunam noship $";
    public static final boolean RCS_ID_RECORDED = VersionInfo.recordClassVersion(RCS_ID, "oracle.apps.fnd.framework.toolbox.tutorial2.server");
    public FwkTbxNewSkillsVODefImpl(String name) {
        super(name);
    }

    /**This is the default constructor (do not remove)
     */
    public FwkTbxNewSkillsVODefImpl() {
    }
}
