/*========================================================================+
 |   Copyright (c) 2001, 2020 Oracle Corporation, Redwood Shores, CA, USA |
 |                      All rights reserved.                              |
 +========================================================================+
 |  HISTORY                                                               |
 | 5-Nov-2014 SRSIDDAM Created.                                           |
 +========================================================================+
 */
package oracle.apps.fnd.framework.toolbox.tutorial2.server;

import oracle.apps.fnd.common.VersionInfo;
import oracle.apps.fnd.framework.server.OAEntityImpl;

import oracle.jbo.AttributeList;
import oracle.jbo.Key;
import oracle.jbo.RowIterator;
import oracle.jbo.domain.BlobDomain;
import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
import oracle.jbo.server.EntityDefImpl;
import oracle.jbo.server.TransactionEvent;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FwkTbxNewEMployeeEOImpl extends OAEntityImpl {
    public static final int EMPLOYEEID = 0;
    public static final String RCS_ID = "$Header: FwkTbxNewEMployeeEOImpl.java 120.0.12020000.1 2020/01/08 05:54:20 spunam noship $";
    public static final boolean RCS_ID_RECORDED = VersionInfo.recordClassVersion(RCS_ID, "%oracle.apps.fnd.framework.toolbox.tutorial2.server%");
    public static final int TITLE = 1;
    public static final int FIRSTNAME = 2;
    public static final int MIDDLENAMES = 3;
    public static final int LASTNAME = 4;
    public static final int FULLNAME = 5;
    public static final int EMAILADDRESS = 6;
    public static final int GUID = 7;
    public static final int MANAGERID = 8;
    public static final int POSITIONCODE = 9;
    public static final int SALARY = 10;
    public static final int STARTDATE = 11;
    public static final int ENDDATE = 12;
    public static final int LASTUPDATEDATE = 13;
    public static final int LASTUPDATEDBY = 14;
    public static final int CREATIONDATE = 15;
    public static final int CREATEDBY = 16;
    public static final int LASTUPDATELOGIN = 17;
    public static final int EMPPHOTO = 18;
    public static final int FWKTBXNEWEMPADDRESSEO = 19;
    public static final int FWKTBXNEWEMPSKILLSEO = 20;
    public static final int FWKTBXNEWEMPTRAININGSEO = 21;
    public static final int FWKTBXNEWEDUCATIONEO = 22;
    public static final int FWKTBXNEWEXPERIENCEEO = 23;
    public static final int FWKTBXNEWASSETEO = 24;
    private static FwkTbxNewEMployeeEODefImpl mDefinitionObject;

    /**This is the default constructor (do not remove)
     */
    public FwkTbxNewEMployeeEOImpl() {
    }


    /**Retrieves the definition object for this instance class.
     */
    public static synchronized EntityDefImpl getDefinitionObject() {
        if (mDefinitionObject == null) {
            mDefinitionObject = (FwkTbxNewEMployeeEODefImpl)EntityDefImpl.findDefObject("oracle.apps.fnd.framework.toolbox.tutorial2.server.FwkTbxNewEMployeeEO");
        }
        return mDefinitionObject;
    }

    /**Add attribute defaulting logic in this method.
     */
    public void create(AttributeList attributeList) {
        super.create(attributeList);
    }

    /**Add entity remove logic in this method.
     */
    public void remove() {
        super.remove();
    }

    /**Add Entity validation code in this method.
     */
    protected void validateEntity() {
        super.validateEntity();
    }

    /**Add locking logic here.
     */
    public void lock() {
        super.lock();
    }

    /**Custom DML update/insert/delete logic here.
     */
    protected void doDML(int operation, TransactionEvent e) {
        super.doDML(operation, e);
    }

    /**Gets the attribute value for EmployeeId, using the alias name EmployeeId
     */
    public Number getEmployeeId() {
        return (Number)getAttributeInternal(EMPLOYEEID);
    }

    /**Sets <code>value</code> as the attribute value for EmployeeId
     */
    public void setEmployeeId(Number value) {
        setAttributeInternal(EMPLOYEEID, value);
    }

    /**Gets the attribute value for Title, using the alias name Title
     */
    public String getTitle() {
        return (String)getAttributeInternal(TITLE);
    }

    /**Sets <code>value</code> as the attribute value for Title
     */
    public void setTitle(String value) {
        setAttributeInternal(TITLE, value);
    }

    /**Gets the attribute value for FirstName, using the alias name FirstName
     */
    public String getFirstName() {
        return (String)getAttributeInternal(FIRSTNAME);
    }

    /**Sets <code>value</code> as the attribute value for FirstName
     */
    public void setFirstName(String value) {
        setAttributeInternal(FIRSTNAME, value);
    }

    /**Gets the attribute value for MiddleNames, using the alias name MiddleNames
     */
    public String getMiddleNames() {
        return (String)getAttributeInternal(MIDDLENAMES);
    }

    /**Sets <code>value</code> as the attribute value for MiddleNames
     */
    public void setMiddleNames(String value) {
        setAttributeInternal(MIDDLENAMES, value);
    }

    /**Gets the attribute value for LastName, using the alias name LastName
     */
    public String getLastName() {
        return (String)getAttributeInternal(LASTNAME);
    }

    /**Sets <code>value</code> as the attribute value for LastName
     */
    public void setLastName(String value) {
        setAttributeInternal(LASTNAME, value);
    }

    /**Gets the attribute value for FullName, using the alias name FullName
     */
    public String getFullName() {
        return (String)getAttributeInternal(FULLNAME);
    }

    /**Sets <code>value</code> as the attribute value for FullName
     */
    public void setFullName(String value) {
        setAttributeInternal(FULLNAME, value);
    }

    /**Gets the attribute value for EmailAddress, using the alias name EmailAddress
     */
    public String getEmailAddress() {
        return (String)getAttributeInternal(EMAILADDRESS);
    }

    /**Sets <code>value</code> as the attribute value for EmailAddress
     */
    public void setEmailAddress(String value) {
        setAttributeInternal(EMAILADDRESS, value);
    }

    /**Gets the attribute value for Guid, using the alias name Guid
     */
    public String getGuid() {
        return (String)getAttributeInternal(GUID);
    }

    /**Sets <code>value</code> as the attribute value for Guid
     */
    public void setGuid(String value) {
        setAttributeInternal(GUID, value);
    }

    /**Gets the attribute value for ManagerId, using the alias name ManagerId
     */
    public Number getManagerId() {
        return (Number)getAttributeInternal(MANAGERID);
    }

    /**Sets <code>value</code> as the attribute value for ManagerId
     */
    public void setManagerId(Number value) {
        setAttributeInternal(MANAGERID, value);
    }

    /**Gets the attribute value for PositionCode, using the alias name PositionCode
     */
    public String getPositionCode() {
        return (String)getAttributeInternal(POSITIONCODE);
    }

    /**Sets <code>value</code> as the attribute value for PositionCode
     */
    public void setPositionCode(String value) {
        setAttributeInternal(POSITIONCODE, value);
    }

    /**Gets the attribute value for Salary, using the alias name Salary
     */
    public Number getSalary() {
        return (Number)getAttributeInternal(SALARY);
    }

    /**Sets <code>value</code> as the attribute value for Salary
     */
    public void setSalary(Number value) {
        setAttributeInternal(SALARY, value);
    }

    /**Gets the attribute value for StartDate, using the alias name StartDate
     */
    public Date getStartDate() {
        return (Date)getAttributeInternal(STARTDATE);
    }

    /**Sets <code>value</code> as the attribute value for StartDate
     */
    public void setStartDate(Date value) {
        setAttributeInternal(STARTDATE, value);
    }

    /**Gets the attribute value for EndDate, using the alias name EndDate
     */
    public Date getEndDate() {
        return (Date)getAttributeInternal(ENDDATE);
    }

    /**Sets <code>value</code> as the attribute value for EndDate
     */
    public void setEndDate(Date value) {
        setAttributeInternal(ENDDATE, value);
    }

    /**Gets the attribute value for LastUpdateDate, using the alias name LastUpdateDate
     */
    public Date getLastUpdateDate() {
        return (Date)getAttributeInternal(LASTUPDATEDATE);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateDate
     */
    public void setLastUpdateDate(Date value) {
        setAttributeInternal(LASTUPDATEDATE, value);
    }

    /**Gets the attribute value for LastUpdatedBy, using the alias name LastUpdatedBy
     */
    public Number getLastUpdatedBy() {
        return (Number)getAttributeInternal(LASTUPDATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdatedBy
     */
    public void setLastUpdatedBy(Number value) {
        setAttributeInternal(LASTUPDATEDBY, value);
    }

    /**Gets the attribute value for CreationDate, using the alias name CreationDate
     */
    public Date getCreationDate() {
        return (Date)getAttributeInternal(CREATIONDATE);
    }

    /**Sets <code>value</code> as the attribute value for CreationDate
     */
    public void setCreationDate(Date value) {
        setAttributeInternal(CREATIONDATE, value);
    }

    /**Gets the attribute value for CreatedBy, using the alias name CreatedBy
     */
    public Number getCreatedBy() {
        return (Number)getAttributeInternal(CREATEDBY);
    }

    /**Sets <code>value</code> as the attribute value for CreatedBy
     */
    public void setCreatedBy(Number value) {
        setAttributeInternal(CREATEDBY, value);
    }

    /**Gets the attribute value for LastUpdateLogin, using the alias name LastUpdateLogin
     */
    public Number getLastUpdateLogin() {
        return (Number)getAttributeInternal(LASTUPDATELOGIN);
    }

    /**Sets <code>value</code> as the attribute value for LastUpdateLogin
     */
    public void setLastUpdateLogin(Number value) {
        setAttributeInternal(LASTUPDATELOGIN, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case EMPLOYEEID:
            return getEmployeeId();
        case TITLE:
            return getTitle();
        case FIRSTNAME:
            return getFirstName();
        case MIDDLENAMES:
            return getMiddleNames();
        case LASTNAME:
            return getLastName();
        case FULLNAME:
            return getFullName();
        case EMAILADDRESS:
            return getEmailAddress();
        case GUID:
            return getGuid();
        case MANAGERID:
            return getManagerId();
        case POSITIONCODE:
            return getPositionCode();
        case SALARY:
            return getSalary();
        case STARTDATE:
            return getStartDate();
        case ENDDATE:
            return getEndDate();
        case LASTUPDATEDATE:
            return getLastUpdateDate();
        case LASTUPDATEDBY:
            return getLastUpdatedBy();
        case CREATIONDATE:
            return getCreationDate();
        case CREATEDBY:
            return getCreatedBy();
        case LASTUPDATELOGIN:
            return getLastUpdateLogin();
        case EMPPHOTO:
            return getEmpPhoto();
        case FWKTBXNEWEDUCATIONEO:
            return getFwkTbxNewEducationEO();
        case FWKTBXNEWASSETEO:
            return getFwkTbxNewAssetEO();
        case FWKTBXNEWEMPSKILLSEO:
            return getFwkTbxNewEmpSkillsEO();
        case FWKTBXNEWEMPADDRESSEO:
            return getFwkTbxNewEmpAddressEO();
        case FWKTBXNEWEMPTRAININGSEO:
            return getFwkTbxNewEmpTrainingsEO();
        case FWKTBXNEWEXPERIENCEEO:
            return getFwkTbxNewExperienceEO();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case EMPLOYEEID:
            setEmployeeId((Number)value);
            return;
        case TITLE:
            setTitle((String)value);
            return;
        case FIRSTNAME:
            setFirstName((String)value);
            return;
        case MIDDLENAMES:
            setMiddleNames((String)value);
            return;
        case LASTNAME:
            setLastName((String)value);
            return;
        case FULLNAME:
            setFullName((String)value);
            return;
        case EMAILADDRESS:
            setEmailAddress((String)value);
            return;
        case GUID:
            setGuid((String)value);
            return;
        case MANAGERID:
            setManagerId((Number)value);
            return;
        case POSITIONCODE:
            setPositionCode((String)value);
            return;
        case SALARY:
            setSalary((Number)value);
            return;
        case STARTDATE:
            setStartDate((Date)value);
            return;
        case ENDDATE:
            setEndDate((Date)value);
            return;
        case LASTUPDATEDATE:
            setLastUpdateDate((Date)value);
            return;
        case LASTUPDATEDBY:
            setLastUpdatedBy((Number)value);
            return;
        case CREATIONDATE:
            setCreationDate((Date)value);
            return;
        case CREATEDBY:
            setCreatedBy((Number)value);
            return;
        case LASTUPDATELOGIN:
            setLastUpdateLogin((Number)value);
            return;
        case EMPPHOTO:
            setEmpPhoto((BlobDomain)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }

    /**Gets the associated entity oracle.jbo.RowIterator
     */
    public RowIterator getFwkTbxNewEmpAddressEO() {
        return (RowIterator)getAttributeInternal(FWKTBXNEWEMPADDRESSEO);
    }

    /**Gets the associated entity oracle.jbo.RowIterator
     */
    public RowIterator getFwkTbxNewEmpSkillsEO() {
        return (RowIterator)getAttributeInternal(FWKTBXNEWEMPSKILLSEO);
    }

    /**Gets the associated entity oracle.jbo.RowIterator
     */
    public RowIterator getFwkTbxNewEmpTrainingsEO() {
        return (RowIterator)getAttributeInternal(FWKTBXNEWEMPTRAININGSEO);
    }

    /**Gets the associated entity oracle.jbo.RowIterator
     */
    public RowIterator getFwkTbxNewEducationEO() {
        return (RowIterator)getAttributeInternal(FWKTBXNEWEDUCATIONEO);
    }

    /**Gets the associated entity oracle.jbo.RowIterator
     */
    public RowIterator getFwkTbxNewExperienceEO() {
        return (RowIterator)getAttributeInternal(FWKTBXNEWEXPERIENCEEO);
    }

    /**Gets the attribute value for EmpPhoto, using the alias name EmpPhoto
     */
    public BlobDomain getEmpPhoto() {
        return (BlobDomain)getAttributeInternal(EMPPHOTO);
    }

    /**Sets <code>value</code> as the attribute value for EmpPhoto
     */
    public void setEmpPhoto(BlobDomain value) {
        setAttributeInternal(EMPPHOTO, value);
    }

    /**Gets the associated entity oracle.jbo.RowIterator
     */
    public RowIterator getFwkTbxNewAssetEO() {
        return (RowIterator)getAttributeInternal(FWKTBXNEWASSETEO);
    }

    /**Creates a Key object based on given key constituents
     */
    public static Key createPrimaryKey(Number employeeId) {
        return new Key(new Object[]{employeeId});
    }
}
