package oracle.apps.fnd.framework.toolbox.tutorial2.server;
/*===========================================================================+
 | Copyright (c) 2012, 2020 Oracle Corporation, Redwood Shores, CA, USA             |
 | All rights reserved.                                                       |
 +============================================================================+
 | HISTORY                                                                    |
 | 8/19/19 ychauhan created                                                   |
 |===========================================================================*/
import oracle.apps.fnd.common.VersionInfo;
import oracle.apps.fnd.framework.server.OAViewRowImpl;

import oracle.jbo.domain.Date;
import oracle.jbo.domain.Number;
import oracle.jbo.server.AttributeDefImpl;
// ---------------------------------------------------------------------
// ---    File generated by Oracle ADF Business Components Design Time.
// ---    Custom code may be added to this class.
// ---    Warning: Do not modify method signatures of generated methods.
// ---------------------------------------------------------------------
public class FwkTbxNewEmpEnrollTrainingVORowImpl extends OAViewRowImpl {
    public static final String RCS_ID = "$Header: FwkTbxNewEmpEnrollTrainingVORowImpl.java 120.0.12020000.1 2020/01/08 05:45:41 spunam noship $";
    public static final boolean RCS_ID_RECORDED = VersionInfo.recordClassVersion(RCS_ID, "oracle.apps.fnd.framework.toolbox.tutorial2.server");
    public static final int EMPTRAININGID = 0;
    public static final int TRAININGID = 1;
    public static final int EMPLOYEEID = 2;
    public static final int STATUS = 3;
    public static final int STARTDATE = 4;
    public static final int ENROLLEDDATE = 5;
    public static final int ENDDATE = 6;
    public static final int CERTIFICATION = 7;

    /**This is the default constructor (do not remove)
     */
    public FwkTbxNewEmpEnrollTrainingVORowImpl() {
    }

    /**Gets FwkTbxNewEmpTrainingsEO entity object.
     */
    public FwkTbxNewEmpTrainingsEOImpl getFwkTbxNewEmpTrainingsEO() {
        return (FwkTbxNewEmpTrainingsEOImpl)getEntity(0);
    }

    /**Gets the attribute value for EMP_TRAINING_ID using the alias name EmpTrainingId
     */
    public Number getEmpTrainingId() {
        return (Number) getAttributeInternal(EMPTRAININGID);
    }

    /**Sets <code>value</code> as attribute value for EMP_TRAINING_ID using the alias name EmpTrainingId
     */
    public void setEmpTrainingId(Number value) {
        setAttributeInternal(EMPTRAININGID, value);
    }

    /**Gets the attribute value for TRAINING_ID using the alias name TrainingId
     */
    public Number getTrainingId() {
        return (Number) getAttributeInternal(TRAININGID);
    }

    /**Sets <code>value</code> as attribute value for TRAINING_ID using the alias name TrainingId
     */
    public void setTrainingId(Number value) {
        setAttributeInternal(TRAININGID, value);
    }

    /**Gets the attribute value for EMPLOYEE_ID using the alias name EmployeeId
     */
    public Number getEmployeeId() {
        return (Number) getAttributeInternal(EMPLOYEEID);
    }

    /**Sets <code>value</code> as attribute value for EMPLOYEE_ID using the alias name EmployeeId
     */
    public void setEmployeeId(Number value) {
        setAttributeInternal(EMPLOYEEID, value);
    }

    /**Gets the attribute value for STATUS using the alias name Status
     */
    public String getStatus() {
        return (String) getAttributeInternal(STATUS);
    }

    /**Sets <code>value</code> as attribute value for STATUS using the alias name Status
     */
    public void setStatus(String value) {
        setAttributeInternal(STATUS, value);
    }

    /**Gets the attribute value for START_DATE using the alias name StartDate
     */
    public Date getStartDate() {
        return (Date) getAttributeInternal(STARTDATE);
    }

    /**Sets <code>value</code> as attribute value for START_DATE using the alias name StartDate
     */
    public void setStartDate(Date value) {
        setAttributeInternal(STARTDATE, value);
    }

    /**Gets the attribute value for ENROLLED_DATE using the alias name EnrolledDate
     */
    public Date getEnrolledDate() {
        return (Date) getAttributeInternal(ENROLLEDDATE);
    }

    /**Sets <code>value</code> as attribute value for ENROLLED_DATE using the alias name EnrolledDate
     */
    public void setEnrolledDate(Date value) {
        setAttributeInternal(ENROLLEDDATE, value);
    }

    /**Gets the attribute value for END_DATE using the alias name EndDate
     */
    public Date getEndDate() {
        return (Date) getAttributeInternal(ENDDATE);
    }

    /**Sets <code>value</code> as attribute value for END_DATE using the alias name EndDate
     */
    public void setEndDate(Date value) {
        setAttributeInternal(ENDDATE, value);
    }

    /**Gets the attribute value for CERTIFICATION using the alias name Certification
     */
    public String getCertification() {
        return (String) getAttributeInternal(CERTIFICATION);
    }

    /**Sets <code>value</code> as attribute value for CERTIFICATION using the alias name Certification
     */
    public void setCertification(String value) {
        setAttributeInternal(CERTIFICATION, value);
    }

    /**getAttrInvokeAccessor: generated method. Do not modify.
     */
    protected Object getAttrInvokeAccessor(int index,
                                           AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case EMPTRAININGID:
            return getEmpTrainingId();
        case TRAININGID:
            return getTrainingId();
        case EMPLOYEEID:
            return getEmployeeId();
        case STATUS:
            return getStatus();
        case STARTDATE:
            return getStartDate();
        case ENROLLEDDATE:
            return getEnrolledDate();
        case ENDDATE:
            return getEndDate();
        case CERTIFICATION:
            return getCertification();
        default:
            return super.getAttrInvokeAccessor(index, attrDef);
        }
    }

    /**setAttrInvokeAccessor: generated method. Do not modify.
     */
    protected void setAttrInvokeAccessor(int index, Object value,
                                         AttributeDefImpl attrDef) throws Exception {
        switch (index) {
        case EMPTRAININGID:
            setEmpTrainingId((Number)value);
            return;
        case TRAININGID:
            setTrainingId((Number)value);
            return;
        case EMPLOYEEID:
            setEmployeeId((Number)value);
            return;
        case STATUS:
            setStatus((String)value);
            return;
        case STARTDATE:
            setStartDate((Date)value);
            return;
        case ENROLLEDDATE:
            setEnrolledDate((Date)value);
            return;
        case ENDDATE:
            setEndDate((Date)value);
            return;
        case CERTIFICATION:
            setCertification((String)value);
            return;
        default:
            super.setAttrInvokeAccessor(index, value, attrDef);
            return;
        }
    }
}
